### ISSUE TITLE
Allow to type the server services

### ISSUE THREAD

**Issue by Bryanoxx** [nuxt-modules/supabase#100]
Hello, first thing first : thank you for this awesome Nuxt Module ! 🔥 

I would love to be able to type the service services, using the auto-generated Database interface : https://supabase.com/docs/reference/javascript/typescript-support

I'm using this to type the client-side `useSupabaseClient` composable, and I think it's also very useful to have it on the server-side.

For example : 
```ts
import type { Database } from '~~/types/database.types'; // Importing the auto-generated Database interface
import { serverSupabaseServiceRole } from '#supabase/server'

export default eventHandler(async (event) => {
  const client = serverSupabaseServiceRole<Database>(event) // Passing the global "Database" type
  const { data } = await client.from('rls-protected-table').select() // "data" is typed
  return { sensitiveData: data }
})
```

Thank you and have a great day!

**Comment by Bryanoxx** [comment]
For those who want to already have the server services typed, here is what I'm currently doing :

```ts
import type { Database } from '~~/types/database.types'
import type { SupabaseClient } from '@supabase/supabase-js'
import { serverSupabaseServiceRole } from '#supabase/server'

const supabaseClient = serverSupabaseServiceRole(event) as unknown as SupabaseClient<Database>
```

**Comment by larbish** [comment]
Should be good with `v0.2.3`.

`const supabaseClient = serverSupabaseServiceRole<Database>(event) `
