### ISSUE TITLE
Netlify issues

### ISSUE THREAD

**Issue by larbish** [nuxt-modules/supabase#101]
nuxt/bridge#277 
#80
#95 
nuxt/framework#98
nuxt/nuxt.js#10952 
nuxt/nuxt.js#10976

**Comment by Mokkapps** [comment]
I'm really looking forward for fixes of these issues

**Comment by getmoredigital** [comment]
I needed this resolved and was still having issues with #98; manually adding the cookies seems to have it resolved. Here my test project: https://github.com/getmoredigital/netlify_nuxt3netlify_workaround for reference.

**Comment by jrsamuel** [comment]
@getmoredigital Thank you, thank you.  I was stuck on this forever and your "hack" saved the day.  I hope they get this fixed soon!

**Comment by larbish** [comment]
Those issues might be solved by https://github.com/nuxt/framework/issues/8705

**Comment by anderslutzhoft** [comment]
Most of the above issues are still persisting. is there any schedule for releasing bug fixes?
