### ISSUE TITLE
Nuxt 3 Static Site Login

### ISSUE THREAD

**Issue by darrenpaul** [nuxt-modules/supabase#103]
Hello I'm having issues with trying to login using Nuxt 3, Supabase and a static site.
It works when running DEV, but when running `yarn generate` and then `yarn preview` I can't seem to login.
I get the following error

package.json
` "@nuxtjs/supabase": "^0.2.2",`
`"nuxt": "3.0.0-rc.11",`

```
entry.fcdd4341.js:1 TypeError: Cannot read properties of null (reading 'id')
    at login.431cd3e5.js:1:4642
    at Ct (entry.fcdd4341.js:1:12486)
    at Ge (entry.fcdd4341.js:1:12564)
    at m (entry.fcdd4341.js:1:22057)
    at Ct (entry.fcdd4341.js:1:12494)
    at Wl (entry.fcdd4341.js:1:14124)
    ```

Thanks

**Comment by darrenpaul** [comment]
So figured out what the issue was.

After generating and previewing, the `sb-refresh-token`, `sb-access-token` and the user are not set 

So I did the following to fix my issue
```
 const { data, error } = await client.auth.signInWithPassword({
    email: email.value,
    password: password.value
  })
  user.value = data.user
  accessToken.value = data.session.access_token
  refreshToken.value = data.session.refresh_token
  ```
  
  Is this intentional or am I doing something wrong or is this a bug?

**Comment by larbish** [comment]
Indeed, you can't use this module to login in static mode because cookies are set on server side: https://github.com/nuxt-modules/supabase/blob/main/src/runtime/server/api/session.ts

**Comment by pmcp** [comment]
Can you please advice us how to handle this?
