### ISSUE TITLE
Warning about the source map pointing to missing files.

### ISSUE THREAD

**Issue by scalemaildev** [nuxt-modules/supabase#111]
This is on @nuxtjs/supabase 0.2.5 and nuxt3 rc 13.

![Screenshot_20221117_102928](https://user-images.githubusercontent.com/15042849/202502885-52051cd1-31bd-4f19-a8bd-c9d6ae984d65.png)

Haven't encountered any fatal errors due to it yet.

**Comment by Ponkhy** [comment]
Same here for me

**Comment by larbish** [comment]
Should be fixed in the last module version with Nuxt 3 stable (`v3.0.0`). Please reopen if needed.
