### ISSUE TITLE
 useSupabaseUser is not defined, after upgrading Nuxt to v3.0.0

### ISSUE THREAD

**Issue by nosizejosh** [nuxt-modules/supabase#116]
my app was working fine until I upgraded to nuxt v 3.0.0 and now app is broken with the following error:

> uncaught error during route navigation: ReferenceError: useSupabaseUser is not defined 

private route guard code remains unchanged as seen below:

```
export default defineNuxtRouteMiddleware((to, from) => {
  const exemptRegRoute = Object.keys(to.query).includes("fromEmail");
  const publicRoutes = [
    "signin",
    "signup",
    "forgotpass",
    "confirm",
    "logout",
    "faq",
  ];
  const privateRoute = !publicRoutes.includes(to.name);
  const user = useSupabaseUser();
  watchEffect(() => {
    if (!user.value && privateRoute && !exemptRegRoute) {
      // if not signed in and attemting to visit private route
      // reroute to login saving the current destination in the redirect query param
      return navigateTo({ name: "signin", query: { redirect: to.path } });
    }
  });
});
```

seems auto import of `const user = useSupabaseUser();` is now broken;

### Version
@nuxtjs/supabase: v0.2.5
nuxt: v3.0.0

Any ideas on how to resolve this?

**Comment by larbish** [comment]
Can you try to remove your `node_modules`, `.nuxt` folder and your lock file ?

**Comment by nosizejosh** [comment]
@larbish I removed all 3, run yarn install and then yarn dev but same error

**Comment by nosizejosh** [comment]
@larbish commenting out the route guard code leads to another error 

> ReferenceError: useSupabaseClient is not defined

  also related to nuxt/supabase

**Comment by nosizejosh** [comment]
@larbish can this be due to deprecated autorimports from https://github.com/nuxt/framework/releases breaking changes?

**Comment by nosizejosh** [comment]
In an attempt to create the reproduction I saw this error on nuxt config, I think this may be the issue. ![image](https://user-images.githubusercontent.com/392227/203364601-2727237e-bffd-4745-9994-fa57ee3e8725.png)
I am looking for the new config options now. What do you think?

**Comment by larbish** [comment]
Indeed, here is the issue. In nuxt 3,all modules should be in `modules` field.

**Comment by nosizejosh** [comment]
I just did that but error now is 

> Cannot start nuxt:  Cannot read properties of undefined (reading 'push')

going to try removing and reinstalling

**Comment by nosizejosh** [comment]
now getting 

> TypeError: supabase.auth.user is not a function

is there a link to a working repo with nuxt 3.0.0 I can follow?

**Comment by larbish** [comment]
Just read and follow the documentation: http://supabase.nuxtjs.org

**Comment by nosizejosh** [comment]
@larbish looks like 

> useSupabaseAuthClient 

from your documentation here https://supabase.nuxtjs.org/usage/composables/use-supabase-auth-client is deprecated?

**Comment by larbish** [comment]
You can check the last release for more info: https://github.com/nuxt-modules/supabase/releases/tag/v0.3.0
