### ISSUE TITLE
don't work on nuxt 3.0.0-rc.14, ok on 3.0.0-rc.13

### ISSUE THREAD

**Issue by bnbc** [nuxt-modules/supabase#118]
### Version
@nuxtjs/supabase: 0.3.0
nuxt: 3.0.0-rc.14

### Issue
Just adding module in `nuxt.config.ts` and launch server with `yarn dev -o` cause this error : `Cannot read properties of undefined (reading 'supabase')`

### Fix
Change nuxt: 3.0.0-rc.14 to nuxt: 3.0.0-rc.13 in package.json
```
sudo rm -rf node_modules/
yarn install
yarn dev -o
```

**Comment by larbish** [comment]
Can you try with the Nuxt3 stable version (v3.0.0) ?

**Comment by bnbc** [comment]
It's ok ! my bad, didn't see the 3.0.0 nuxt 3 stable version.

Thks!
