### ISSUE TITLE
user recognized by server, but not by front-end

### ISSUE THREAD

**Issue by tnntwister** [nuxt-modules/supabase#130]
### Version
@nuxtjs/supabase: ^2.1.2
nuxt: ^3.0.0

### Steps to reproduce

i have a api route called /api/user/me, which recovers my user data : 

```
import { serverSupabaseClient, serverSupabaseUser } from "#supabase/server";

export default eventHandler(async (event) => {
    const client = serverSupabaseClient(event);
    let user = await serverSupabaseUser(event);

    return { user: user };
});
```
if i make a http request with http://my.domain.tld/api/user/me, it's ok, i have all my data in a beautiful json.

![Capture d’écran 2022-12-16 à 20 28 02](https://user-images.githubusercontent.com/40766799/208174189-04f0612c-d400-47ea-8fd3-0a533ce95ab7.png)

then i want to use my api elsewhere in the front end component part with : 
```
await useFetch("/api/user/me"); 
```
the promise return null. 

### What is Expected?

the api call should return the user data with an direct call and with a fetch call. 

### What is actually happening?

I think the issue comes from the storage key. 
in front end, the storage key should be sb-localhost-auth-token, whereas the supabase data is stocked with this key : sb-afkagvuhjqznkffqwwqc-auth-token.
I don't know how to tell the module that my project serves the front end as well as the back end, so that it should share the same key name.

**Comment by larbish** [comment]
Could you try to send headers on fetch:

```
const { data } = await useFetch('/api/user/me', {
  headers: useRequestHeaders(['cookie'])
})
```
