### ISSUE TITLE
Vendor locked in to use server routes? How to use with Cloudflare pages?

### ISSUE THREAD

**Issue by itszooper** [nuxt-modules/supabase#132]
Since this module is using server routes https://github.com/nuxt-modules/supabase/blob/main/src/runtime/server/api/session.ts, it fails on a lot of platforms, which are not vercel or netlify. This is a very strict vendor lock in tbh

Isnt this supposed to be a client side sdk, which is how the actual supabase sdk works.

Is it possible to get this working in cloudflare pages?

**Comment by MikeBman** [comment]
@itszooper  Any luck getting this to work with cloudflare pages?

**Comment by itszooper** [comment]
@larbish Any help with this one Please? This looks like a very weird bug and I have no idea how to proceed, I actually built fixed my entire auth system for my application and when I finally pushed it to my cloudflare account, it didnt work 😢 >

**Comment by RihanArfan** [comment]
Nuxt server routes work fine on Cloudflare Pages. Make sure you're running the build script and not generate.
