### ISSUE TITLE
Supabase doesn't play nice with preset:cloudflare - Keys are not taken from .env and cookies are not stored on website

### ISSUE THREAD

**Issue by altryne** [nuxt-modules/supabase#133]
I'm not sure what I'm missing, but asking around in Cloudflare discord, they didn't have a good answer. 

nuxt supabase setup works locally with `npm run dev` using url/key combo in .env. 

Deploying to a worker didn't work, as workers don't have `process.env` so.. nuxt supabase can't even be initiated. 

ok, adding the keys to 
`supabase:` entry on nuxt config, again, works locally, doesn't seem to work on build. 

hardcoding the keys into nuxt.config as strings, seems to... work on auth, but the app is not aware of the logged in state. 

by which I mean, I see the response in network tab, but.. my nuxt app is not aware of it, auth middleware is not picking up that a user is authenticated and nothing works locally.

HELP

**Comment by altryne** [comment]
Some more insight, it seems that.. even though supabase auth succeeds, the cookies are not stored on my domain when hosted via workers. 

Here's a local example

<img width="1065" alt="CleanShot 2022-12-20 at 12 37 36@2x" src="https://user-images.githubusercontent.com/463317/208752182-a31b771a-87aa-4a8c-a914-be5b62da62cf.png">


Here's the same example on cloudflare workers
<img width="1033" alt="CleanShot 2022-12-20 at 12 38 47@2x" src="https://user-images.githubusercontent.com/463317/208752244-6192212a-de09-407b-ac78-c45c4e7c1991.png">


The sb-access token and sb-refresh token are not stored via cloudflare.

**Comment by altryne** [comment]
It seems to be because of this: 
`/api/_supabase/session` API that's coming from nuxtSupabase in `session.mjs` 

This seems to not "save" any cookies on cloudflare no matter how I twist it.

I've tried adding domain, playing with cookie name, and nothing. 

@danielroe help 😢?

**Comment by altryne** [comment]
I kept going with debugging this and getting to the bottom. 
Cloudflare stored nitro routes DO set cookies, i was able to set them myself. 

I created a redirect with hybrid rendering :
```
  routeRules: {
    '/api/_supabase/session': { redirect: '/api/session' }, // redirect internal supabase session storage to our own
  },
```

And printed everything that comes in, and it's weirdly looks like this: 
I'm not sure if this is the result of the redirect or what

<img width="1283" alt="CleanShot 2022-12-21 at 10 34 28@2x" src="https://user-images.githubusercontent.com/463317/208968403-d33a0991-461a-435a-8018-d524d4ba7a95.png">

**Comment by altryne** [comment]
Not sure what's going on, but H3 seems to... not send the body in a parsable way when running via miniflare
I put a breakpoint on my compiled code where it sends the sessions to `/api/_supabase/session` and looks ok: 
<img width="667" alt="CleanShot 2022-12-21 at 11 37 46@2x" src="https://user-images.githubusercontent.com/463317/208979154-e76e0c3e-4ea5-42ce-ad2f-b4bc439f2b4e.png">

But then putting a breakpoint on the handler server side, I get a Uint8Array instead of something parsable. 
So readBody doesn't "know" that there's a session there, even though there is. 

![CleanShot 2022-12-21 at 11 36 42@2x](https://user-images.githubusercontent.com/463317/208979064-9677644e-83e4-45af-b55d-cadb27573c90.png)

**Comment by altryne** [comment]
Ok a long winded debug session, but I think... I was able to add a workaround (but this is still a bug, I think https://github.com/unjs/h3/issues/144 is the right place for that bug to exist) 

Here's what I did: 
1. copied `@nuxtjs/supabase/dist/runtime/server/api/session.mjs` to my own api route in `/api/session.js` 
2. created a redirect to it from the above in nuxtConfig with routeRules: 
```
  routeRules: {
    '/api/_supabase/session': { redirect: '/api/session' }, // redirect internal supabase session storage to our own
  },
```
3. checked to see if the incoming readBody on the above session route doesn't have a "session" which means it's Uint8Array
4. if it is (which means we're likely in CF context) then I parse the UInt8Array into str, and then load to json
5. voila, the cookie is stored, auth works!

**Comment by fayazara** [comment]
@larbish @Atinux  Could you point me to fix this natively without adding workaround wrappers.

**Comment by david8z** [comment]
@altryne Ty for this ❤️  I realized that this only sets the `access-token` not the `refresh-token`.

**Comment by MarianMichalovic** [comment]
Problem with storing cookies on cloudflare, example
```
setCookie(event, 'sb-refresh-token', data.session.refresh_token)
setCookie(event, 'sb-access-token', data.session.access_token)
```
store only first cookie

response header cloudflare, single set-cookie with both values, dont work
![Untitled-1](https://user-images.githubusercontent.com/2250645/220867144-28d80a6d-b4e0-400f-a648-5eaacda4d8ba.png)

response header on local dev, separate set-cookie for each value, work
![image](https://user-images.githubusercontent.com/2250645/220868969-fc4cb639-eb17-426e-9e93-45bf4cbc6360.png)

**Comment by Flawe** [comment]
hey folks, any updates on this? i'm also stuck not being able to deploy an app that otherwise works because it breaks when deployed on CF workers as mentioned above.

**Comment by fayazara** [comment]
Dropped working on supabase because I was not able to get this working and didn't get any update yet on the issue. Tried resolving it myself, but I wasn't able to figure it out.

**Comment by Flawe** [comment]
i think it's a nuxt3 + cf worker issue though, not supabase? still a shame it's not getting any love.

**Comment by altryne** [comment]
@fayazara @Flawe I was chatting w/ @danielroe who graciously gave me some of his time to get to the bottom of this, and it seems that it's now been solved! I'm still testing, but I'm removing my workaround and things seem to be in order. 

It's an upstream dep. so refresh your package-json and it should... work
Solved in https://github.com/unjs/h3/issues/363
