### ISSUE TITLE
Auth user on hosted server doesn't work (That's work only locally)

### ISSUE THREAD

**Issue by ClineResearch** [nuxt-modules/supabase#134]
Version
@nuxtjs/supabase: 0.3.0
nuxt: 3.0.0

Hi!
To illustrate the problem, I installed this nuxt3 app with a magic link authentification:
https://supabase.com/docs/guides/getting-started/tutorials/with-nuxt-3

Auth user is OK on local host, but it doesn't work on Netlify environment for example.
Here this app on Netlify: https://clever-quokka-fb916e.netlify.app
If the user doesn't exist, it will created but it's impossible after to log in with this registered user (no specific error on the console).

Is somebody had such problem?
Thanks.
JF

**Comment by Ahbork** [comment]
I'm having the same issue. In my case the sign-in function works and correctly returns the user - but on my Netlify page the `sb-access-token` cookie is never set, so refreshing the page means the user is no longer logged in.
Would love to know if anyone has found a solution to this.

**Comment by ClineResearch** [comment]
Thanks a lot!
That's work with the solution here : https://github.com/nuxt-modules/supabase/issues/101#issuecomment-1325989728
We are waiting a solution without this hack!

**Comment by larbish** [comment]
Closing in favor of #101
