### ISSUE TITLE
Can this be used with the Pinia module?

### ISSUE THREAD

**Issue by larrasu** [nuxt-modules/supabase#141]
I tried to use this inside a store but always ran into an error with `nuxt instance unavailable`. Has anyone tried this so far?

`stores/category.js`
```js
const supabase = useSupabaseClient();

export const useCategoryStore = defineStore({
  id: "category",
  state: () => ({
    categories: [],
    category: {},
  }),
  getters: {},
  actions: {
    async fetchCategories() {
      const { data, error } = await supabase
        .from("categories")
        .select("id, name, plural_name");
      if (error) {
        console.log(error);
      }
      this.categories = data;
    },
  },
});
```

The `useSupabaseClient()` doesn't also work inside `composables` and I will get the `nuxt instance unavailable` error. Is this an error with the module or with Nuxt?

**Comment by valpet** [comment]
I receive the same error, trying to fetch and subscribe in a store instead of in a component.

**Comment by Oluwafemi21** [comment]
Working fix using pinia but with composition api set up 
`
// store/user.js
import { defineStore } from "pinia";
import { ref } from "vue";

export const useUserStore = defineStore("user", () => {
    const user = ref(null);
    const client = useSupabaseAuthClient();
    const router = useRouter();

    async function login(username, password) {
        await client.auth
            .signInWithPassword({
                email: username,
                password: password,
            })
            .then(({ data }) => {
                user.value = data.user;
            })
            .catch((err) => {
                console.log(err);
            });
    }
 return { user, login, };
});
`

**Comment by larrasu** [comment]
@Oluwafemi21 Thank you! Never thought of this lol.
