### ISSUE TITLE
Netlify deployment: Randomly returns 404 on requesting my-site.netlify.app/api/_supabase/session

### ISSUE THREAD

**Issue by anderslutzhoft** [nuxt-modules/supabase#146]
### Version
"@nuxtjs/supabase": "^0.3.0",
"nuxt": "3.0.0"

### Reproduction Link

N/A

### Steps to reproduce

Make an auth request using useSupabaseClient().auth.signInWithPassword(), or useSupabaseClient().auth.signOut().

### What is Expected?
Requests to APIs is expected to be stable.

### What is actually happening?
When deoplyed to Netlify, using eg. useSupabaseClient().auth.signInWithPassword() randomly returns a 404 requesting *my-site*.netlify.app/api/_supabase/session.
A page refresh seems to solve the issue until next auth event.

Chrome console output:
POST https://budgetpie-beta.netlify.app/api/_supabase/session 404

Uncaught (in promise) FetchError: 404  (/api/_supabase/session)
    at async Object.callback (entry.d286fcba.js:9:118483)

Aside from needing this workaround #144 everything works fine on local deployment.

**Comment by bauhem** [comment]
Same here, using Netlify, "@nuxtjs/supabase": "0.3.0" and  "nuxt": "^3.0.0"

**Comment by bauhem** [comment]
I can confirm that bug appear on Netlify and not on Vercel. My nuxt supabase setup work in Vercel.

**Comment by bauhem** [comment]
We need to use : nuxt build instead of nuxt generate to make this work on Netlify

**Comment by kiselev3** [comment]
I'm getting the same 404 error if I locally run nuxt generate and upload everthing from dist folder to vercel or netlify.

![image](https://user-images.githubusercontent.com/114939572/214953384-69a78e25-2aed-4a49-87b8-6194dfd757da.png)

![image](https://user-images.githubusercontent.com/114939572/214953607-00b6d022-7852-4b64-b792-a18513cda902.png)

**Comment by Aybee5** [comment]
Make sure you are using `pnpm build` script to deploy

**Comment by marc-tech** [comment]
+1

**Comment by wrightd** [comment]
I'm seeing this same issue when building/deploying for Cloudflare Pages. I'm using build then generate to create a static site.
Does next-supabase support static (JAMSTACK-style) deployment? It looks like it's requiring an API accessible via POST.
Is there some switch you need to set to make it support static sites, or is that just not available right now?

**Comment by Aybee5** [comment]
> I'm seeing this same issue when building/deploying for Cloudflare Pages. I'm using build then generate to create a static site.
> Does next-supabase support static (JAMSTACK-style) deployment? It looks like it's requiring an API accessible via POST.
> Is there some switch you need to set to make it support static sites, or is that just not available right now?
> 


I will recommend you update your build command to `npm run build` based on this https://nitro.unjs.io/deploy/providers/netlify

**Comment by marc-tech** [comment]
I guess this is a proxy probleme : https://docs.netlify.com/routing/redirects/rewrites-proxies/

**Comment by 1boch1** [comment]
> We need to use : nuxt build instead of nuxt generate to make this work on Netlify

I'm using Nuxt3 (SSR: false) and SupabaseNuxt on a Nginx server hosted on Oracle Cloud, with "npm run generate" I get that error (404 /api/_supabase....) and with "npm run build" the index.html file doesn't get generated, so how can I deploy using "npm run build" if it is the solution? Thanks

**Comment by 1boch1** [comment]
> I'm seeing this same issue when building/deploying for Cloudflare Pages. I'm using build then generate to create a static site.
> Does next-supabase support static (JAMSTACK-style) deployment? It looks like it's requiring an API accessible via POST.
> Is there some switch you need to set to make it support static sites, or is that just not available right now?

Did you find something new?
