### ISSUE TITLE
Unable to get session

### ISSUE THREAD

**Issue by dustin-we** [nuxt-modules/supabase#147]
### Version
@nuxtjs/supabase: v0.3.0
nuxt: v3.1.0

### Steps to reproduce

create a Nuxt3 project
install @nuxtjs/supabase
Login a user with OAuth or via Email
try to get the session via either:

```
const client = useSupabaseClient();
const { data } = await client.auth.getSession()
console.log(data.session)
```

or:

```
const client = useSupabaseAuthClient();
const { data } = await client.auth.getSession()
console.log(data.session)
```

### What is Expected?

`data.session` should be an object containing, for example, the JWT. It is in v0.2.6.

### What is actually happening?

`data.session` is null

### Notes

This might be related to #143 

This, for me, also affects Realtime. My realtime subscription will always be anonymous, except if I manually set the auth for it via:

`client.realtime.setAuth('JWT I generated')`

Maybe I am missing something. I would love to fix it, but am rather new to open source. If someone could confirm this is a bug and not a mistake on my end, and maybe point me in the right direction, that would be awesome.

Thanks!

**Comment by marcusarnfast** [comment]
const client = useSupabaseAuthClient();
const { data, error } = await client.auth.getSession();
console.log(data.session);

Works for me 🙋‍♂️ I had some issues too, but realized i forgot auth in client.auth.getSession();
