### ISSUE TITLE
server/api breaks when used with nuxt v3.1.x

### ISSUE THREAD

**Issue by sduduzog** [nuxt-modules/supabase#151]
Here's the logs I got before downgrading nuxt to v3.0.0

```
[nuxt] [request error] [unhandled] [500] main.createClient is not a function
  at serverSupabaseServiceRole (/C:/dev/gits-web/.output/server/chunks/serverSupabaseServiceRole.mjs:10:33)
  at /C:/dev/gits-web/.output/server/chunks/transactions.post.mjs:13:17
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.handler (/C:/dev/gits-web/.output/server/node_modules/h3/dist/index.mjs:840:19)
  at async Server.toNodeHandle (/C:/dev/gits-web/.output/server/node_modules/h3/dist/index.mjs:915:7)
[nuxt] [request error] [unhandled] [500] main.createClient is not a function
  at serverSupabaseServiceRole (/C:/dev/gits-web/.output/server/chunks/serverSupabaseServiceRole.mjs:10:33)
  at /C:/dev/gits-web/.output/server/chunks/transactions.delete.mjs:22:17
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.handler (/C:/dev/gits-web/.output/server/node_modules/h3/dist/index.mjs:840:19)
  at async Server.toNodeHandle (/C:/dev/gits-web/.output/server/node_modules/h3/dist/index.mjs:915:7)
  ```

### Version
@nuxtjs/supabase: v0.3.0
nuxt: v3.1.2

**Comment by larbish** [comment]
Can you try with the last version of the module ? If you are still experiencing this error, please provide a reproduction 🙏

**Comment by sduduzog** [comment]
I'll give it a shot later today (CAT timezone) . I did start on setting up a reproduction repo but I haven't been lucky in reproducing the issue, whether the update works or not, I'll close this issue very shortly

**Comment by blackspike** [comment]
Oh! I have the EXACT same error as @sduduzog – I followed his advice and downgraded nuxt from 3.1.2 to 3.0.0 and it started working again

```
  "devDependencies": {
    "@nuxtjs/supabase": "^0.3.1",
    "@volar/vue-language-plugin-pug": "^1.0.24",
    "nuxt": "^3.1.2",
    "pug": "^3.0.2",
    "sass": "^1.58.0"
  },
```

**Comment by sduduzog** [comment]
I'll try this again this coming weekend, firstly to reproduce and investigate the culprit causing this. I'll mirror your devDependencies too @blackspike in trying this

**Comment by procrates** [comment]
@larbish Issue still exsists on latest version of nuxt 3.2.2. On server I am bypassing RLS with:

```
import { serverSupabaseServiceRole } from '#supabase/server'

export default defineEventHandler(async (event) => {
  const client = serverSupabaseServiceRole(event)
  const { data: { users }, error } = await client.auth.admin.listUsers()
  return users
})
```
Which results in `[nuxt] [request error] [unhandled] [500] main.createClient is not a function`

Using latest nuxt-supabase and nuxt.

**Comment by zkschmitz** [comment]
Same here - tried on 3.1.1 as well if that helps!

**Comment by sduduzog** [comment]
@larbish I'm currently getting this on a production build when using the supabase library directly but transpiling it as per the module. 
![image](https://user-images.githubusercontent.com/48126337/222928183-c61ede81-f2b5-4324-9449-4d1a3e00319b.png)

and with this error while on local dev
![image](https://user-images.githubusercontent.com/48126337/222928328-4c3e84c8-639b-46fb-83b2-783119a32e0b.png)

Maybe this is now due for a review https://github.com/nuxt-modules/supabase/blob/034d7dfaf9f52a08da0ade4bf6d5ed31ec740734/src/module.ts#L121

**Comment by sduduzog** [comment]
@larbish I think I got it!

so I ripped out the module and used the supabase client directly to try figure out what was the issue but followed how the module was setting it up.

I get this error
![image](https://user-images.githubusercontent.com/48126337/222928651-f9790ba7-dd30-4676-97dd-e56b2aa1e61c.png)
when transpiling the supabase library, as per the module, but without transpiling it, everything works fine.

Perhaps its time to review this line https://github.com/nuxt-modules/supabase/blob/034d7dfaf9f52a08da0ade4bf6d5ed31ec740734/src/module.ts#L118

**Comment by zefman** [comment]
Yep I'm getting this as well now

**Comment by kyng-cytro** [comment]
Is this fixed now? just got the same error.

**Comment by sduduzog** [comment]
@kyng-cytro This works for me too, I already had a root endpoint and I just had to re-install and enable the module

**Comment by larbish** [comment]
Hey guys, are you still experiencing this issue in [v0.3.5](https://github.com/nuxt-modules/supabase/releases/tag/v0.3.5) ?
