### ISSUE TITLE
Re-instantiation of the supabase auth client and memory leak?

### ISSUE THREAD

**Issue by trueter** [nuxt-modules/supabase#153]
Hello!
I am investigating an issue that is presenting itself in the following manner:
![image](https://user-images.githubusercontent.com/1976714/219311800-a0a88307-6f2a-4651-8e45-7a0706707ae6.png)

By starting my nuxt app in debugging mode and comparing two memory snapshots I was able to identify an excess amount of timers created:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/1976714/219312144-c985e4d6-02ce-49f7-b770-371578956490.png">

Using the debugger I was able to trace this back to the [startAutoRefresh](https://github.com/supabase/gotrue-js/blob/1ee72310cf165d99a5a0c533e7d2f8d539f0413f/src/GoTrueClient.ts#L1165) function of the supabase gotrue client, which is called everytime the auth client is created.

Here's what I believe happens:
- Each time I call serverSupabaseUser() (per h3 event) a new SupabaseAuthClient is created
- Each time a SupabaseAuthClient is created, a new setInterval timer is started, and they are not cleaned up

My questions are:
Is the creation of a new supabase auth client per request expected?
I see that the supabaseClient is attached to the event [here](https://github.com/nuxt-modules/supabase/blob/main/src/runtime/server/services/serverSupabaseClient.ts#L11). Is there a way we can destroy or clean it up at the end of the request?
Do you have any insight into why it is necessary for the server side code to keep timers running for refresh tokens? Could disabling this be an option?

Thanks!

===
node 19.1.0
nuxt 3.2.0
nuxt/supabase 0.3.1
gotrue-js 2.4.2
supabase/supabase-js 2.7.1

**Comment by Thexumaker** [comment]
Any update on this?

**Comment by trueter** [comment]
Seems to have been adressed by https://github.com/nuxt-modules/supabase/issues/189
Memory consumption is now stable:
<img width="541" alt="image" src="https://github.com/nuxt-modules/supabase/assets/1976714/963b94d0-6614-4996-81cb-d2136a431034">

Would love to hear what others have been observing before closing.
