### ISSUE TITLE
Adding in Auth for the middle ware.

### ISSUE THREAD

**Issue by BroJenuel** [nuxt-modules/supabase#155]
### Is your feature request related to a problem? Please describe.

Authentication is one of the important aspects of creating a website, and since next supports SSR, it seems nuxt3 will become a full fledge front and backend. We have been using superbase now and hoping the auth.

### Describe the solution you'd like

The ability to control users from accessing a page or API depending on their role/access roles

**Comment by larrasu** [comment]
As far as I know, Supabase doesn't support custom roles yet, and the roles you can set currently are `authenticated` and `anon`. Try and check [this repo](https://github.com/supabase-community/supabase-custom-claims) and [this thread](https://github.com/orgs/supabase/discussions/11948#discussioncomment-4802137).
