### ISSUE TITLE
User and session are fetch each time we're focusing the tab

### ISSUE THREAD

**Issue by larbish** [nuxt-modules/supabase#163]

**Comment by casio** [comment]
Actually, both requests - POST /session and GET /user -  are dispatched _twice_ on _each_ focus event.
When logged in, you can see this on the demo: https://n3-supabase.netlify.app/

(which is having its auth callback URL set to https://localhost:3000 currently I believe, so users currently cannot login)

**Comment by j4w8n** [comment]
Likely due to gotrue-js behavior. There is a [PR](https://github.com/supabase/gotrue-js/pull/684) to stop emitting `SIGNED_IN` events on tab focus.
