### ISSUE TITLE
useSupabaseUser returns the user on the server (eg. middleware) but isn't populated on frontend

### ISSUE THREAD

**Issue by MAXOUXAX** [nuxt-modules/supabase#179]
### Version
@nuxtjs/supabase: 0.3.5
nuxt: 3.4.2

### Reproduction Link
Can't really give a reproduction since it seems to happen on any environment and requires email magic link

### Steps to reproduce
1. Get sent a magic link through a forgot password process
2. Click the link, you should be logged in on the website and the user should be available through the useSupabaseUser() method
3. Click the link in the email again, if you have middlewares checking for the value of user, they should work fine, but your frontend won't be able to get the user through useSupabaseUser()

### What is Expected?
The user should be available on the frontend

### What is actually happening?
The user isn't available on the frontend but only on the server

This behavior is very weird, but basically when logging the user value from the middleware, the user is populated on the server, when the middleware runs on the client, it's also populated, but after the hydration process, the user becomes null.
Here's a snippet of my console:
<img width="413" alt="Console" src="https://user-images.githubusercontent.com/24844231/233962553-0f3adcfd-5b51-48eb-a17c-463672fc6630.png">

```ts
export default defineNuxtRouteMiddleware(async (to, _from) => {
  const user = useSupabaseUser();
  if (!user.value) return notLoggedIn(to.path);
  console.log("user =", user.value);
    
  if(process.client){
    setInterval(() => {
      const user = useSupabaseUser();
      console.log("user.value == null ?", user.value == null);
    }, 100)
  }

});
```

The same behavior occurs every time I refresh the page and can only be fixed by deleting the cookies.

**Comment by savy-91** [comment]
Same happens to me

**Comment by Pierre-M** [comment]
I had the exact same issue, FYI the workaround I found (not ideal but it works 🤗 ) : 

```ts
// In my global authentication middleware
export default defineNuxtRouteMiddleware(async (to) => {
  // check is user is landing on your site after authentication funnel
  const isComingFromAuthentication = to.hash.includes("access_token");

  if (isComingFromAuthentication) {
    /*
    Explicitly post SIGNED_IN event to nuxt/supabase session api route.
     */
    const { data } = await useSupabaseAuthClient().auth.getSession();

    await $fetch("/api/_supabase/session", {
      method: "POST",
      body: {
        event: "SIGNED_IN",
        session: data.session,
      },
    });
    const { data: userData } = await useSupabaseAuthClient().auth.getUser();
    useSupabaseUser().value = userData.user;
  }
});

```

**Comment by bart** [comment]
Also facing the same issue which unfortunately is a show stopper on a current project. If I console.log `user.value` it is null but when I console.log the user object instead and check the `ObjectRefImpl` object manually user data is present. Weird

**Comment by bart** [comment]
I came up with a middleware solution that works. Maybe it also helps someone else:

```
export default defineNuxtRouteMiddleware(() => {
  const user = useSupabaseUser()
  const client = useSupabaseAuthClient()

  setTimeout(async () => {
    if (process.client && !user.value) {
      const { data } = await client.auth.getUser()
      user.value = data.user

      if (!user.value) {
        navigateTo('/login')
      }
    }
  })
})
```

**Comment by everettblakley** [comment]
> I came up with a middleware solution that works. Maybe it also helps someone else:
> 
> ```js
> export default defineNuxtRouteMiddleware(() => {
>   const user = useSupabaseUser()
>   const client = useSupabaseAuthClient()
> 
>   setTimeout(async () => {
>     if (process.client && !user.value) {
>       const { data } = await client.auth.getUser()
>       user.value = data.user
> 
>       if (!user.value) {
>         navigateTo('/login')
>       }
>     }
>   })
> })
> ```

Thanks @bart, worked for me!
