### ISSUE TITLE
Is there a way to use the useSupabaseClient and other functions outside of a Nuxt-related component?

### ISSUE THREAD

**Issue by onurusluca** [nuxt-modules/supabase#202]
I am trying to use `const supabase = useSupabaseClient();` in a composable file:

useAuth.ts:
```
const supabase = useSupabaseClient();

  const login = async (email: string, password: string) => {
    try {
      const { data, error } = await supabase.auth.signInWithPassword({
        email,
        password,
      });
      return { data, error };
    } catch (error) {
      console.error("Login error thrown from useAuth.ts:", error);
      throw error;
    }
  };
```

But I am getting this error:
> [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables

Is it not possible to do this or am I doing it wrong?

**Comment by anderslutzhoft** [comment]
I'm getting a similar error when calling the `useSupabaseAuthClient()` composable via a helper function in the utils/ directory, but only if I'm using that helper function in a child component in the components folder.
If I use the helper function from pages/index.vue it works fine.

**Comment by onurusluca** [comment]
Solved this problem:

composables/useAuth.ts :

```
const authClient = useSupabaseClient();
export default function () {
  const signIn = async (email: string, password: string) => {
    try {
      const { data, error } = await authClient.auth.signInWithPassword({
        email,
        password,
      });
      return { data, error };
    } catch (error) {
      console.error("Login error thrown from useAuth.ts:", error);
      throw error;
    }
  };
    return {
    signIn
    }
}
```
