### ISSUE TITLE
Upstream regression? Issue with `useSupabaseUser` related to supabase/gotrue-js@2.44.0

### ISSUE THREAD

**Issue by trueter** [nuxt-modules/supabase#207]
### Version
@nuxtjs/supabase: 0.3.8
nuxt: 3.6.4

### Reproduction Link

See @hedefalk's post: https://github.com/supabase/supabase/issues/15887 (using `supabase/examples/user-management/nuxt3-user-management`)

### Steps to reproduce

In the above thread

### What is Expected?

In my own project I noticed that https://github.com/supabase/gotrue-js/releases/tag/v2.44.0 breaks my login screen, using this pattern:

```js
const user = useSupabaseUser()

watch(
  () => user.value,
  ... // login logic
)
```

### What is actually happening?

`user.value` does not seem to change and my login logic does not run.
Sorry for not providing my own reproduction at this time (it's late), but I wanted to let others know that you can temporarily avoid the issue by pinning:
```json
"overrides": {
  "@supabase/gotrue-js": "2.43.1"
}
```

**Comment by yeonjulee1005** [comment]
@trueter thank you your advise! 
but, in my project (Nuxt 3.6.5) it can't override version gotrue-js.
how should i do :cry:

**Comment by kalwabed** [comment]
I found it works for me. Thanks!
In my case, users cannot run `useSupabaseClient()` when they want to mutate some data in an async function.

If we check the browser console, we may get a warning like _"Multiple GoTrueClient instances detected in the same browser context. It is not an error, but this should be avoided as it may produce undefined behavior when used concurrently under the same storage key."_

if you are using `pnpm`, you can write it in `package.json` file:
```json
"pnpm": {
    "overrides": {
      "@supabase/gotrue-js": "2.43.1"
    }
  }
```

**Comment by diakonovm** [comment]
When I attempt to sign out a user with the client provided by `useSupabaseClient` I am receiving the following warning in the console.

_**Multiple GoTrueClient instances detected in the same browser context. It is not an error, but this should be avoided as it may produce undefined behavior when used concurrently under the same storage key.**_

The error is still persisting after the resolution to `"@supabase/gotrue-js": "2.43.1"`.

Any solutions for this warning?

**Comment by kalwabed** [comment]
> When I attempt to sign out a user with the client provided by useSupabaseClient I am receiving the following warning in the console.

I suppose the warning appears because we are instantiating `useSupabaseClient` or `useSupabaseUser` in multiple places on the same page.

So for the time being I have no problem with it because it does not affect the interaction with Supabase.

**Comment by CptJJ** [comment]
https://github.com/supabase/supabase-js/releases/tag/v2.29.0

Can the nuxt module be updated to reflect the latest changes here? Been struggling to confirm that im loading the old version of gotrue, this issue is causing my app to hang up on the loading screen very frusturating!

**Comment by CptJJ** [comment]
I was able to resolve a lot of my issues related around the gotrue package and elaborated in #209

**Comment by trueter** [comment]
FYI, the [recommended fix](https://github.com/supabase/gotrue-js/issues/455#issuecomment-1652553296) is now:
```json
{
  "overrides": {
    "@supabase/supabase-js": "2.31.0"
  }
}
```
This also addressed another mysterious issue I had with OTP sign ins on my mobile devices even on `gotrue-js@2.43.1`.
Pull request filed under https://github.com/nuxt-modules/supabase/pull/218.

**Comment by andywillekens** [comment]
I'm not using @supabase/supabase-js but @nuxtjs/supabase 0.3.8 but stil getting this problem in firefox/safari (chrome works just fine..)

**Comment by devaamir92** [comment]
any fix?

**Comment by kalwabed** [comment]
> @devaamir92 any fix?

After upgrading to version 1, I no longer see this issue. Thanks to the Nuxt team.

**Comment by devaamir92** [comment]
> > @devaamir92 any fix?
> 
> After upgrading to version 1, I no longer see this issue. Thanks to the Nuxt team.

when upgarde to to version 1 
not found this modules
export { useSupabaseAuthClient } from '../node_modules/@nuxtjs/supabase/dist/runtime/composables/useSupabaseAuthClient';

**Comment by kalwabed** [comment]
>when upgarde to to version 1
not found this modules
export { useSupabaseAuthClient } from '../node_modules/@nuxtjs/supabase/dist/runtime/composables/useSupabaseAuthClient';

I believe that `useSupabaseAuthClient` was removed in [version 1](https://github.com/nuxt-modules/supabase/releases/tag/v1.0.1). I suggest you to read the [documentation](https://supabase.nuxtjs.org) directly.
