### ISSUE TITLE
useSupabaseUser doesn't update after magic link or oAuth on mobile

### ISSUE THREAD

**Issue by sdaoud** [nuxt-modules/supabase#208]
### Version
@nuxtjs/supabase: 0.3.8
nuxt: 3.6.5
iOS version: 16.5.1
Model: iPhone X

### Steps to reproduce

Signing in via oAuth or magic link does not work on iOS Safari. `useSupabaseUser` never updates and the user is never logged in on the client. In contrast, magic links and oAuth _do_ work on Chrome and Safari on MacOS. 

Everything worked perfectly in 0.3.5

### What is Expected?

Signing in via magic link or oAuth should set the value of `useSupabaseUser` to the currently logged in user on iOS Safari

### What is actually happening?

`useSupabaseUser` never updates

**Comment by riemervdzee** [comment]
I'm having the same issue with Google oAuth but With google Chrome on MacOs 😅 

Downgrading `@supabase/gotrue-js` to `2.42.0` resolved my issue. It was previously on `2.44.1` as sub-dependency

Version info: 
@nuxtjs/supabase: 0.3.8
nuxt: 3.6.5

**Comment by IsraelOrtuno** [comment]
Experiencing this with the current version on iOS. When I get the magic link and click on it on my Gmail app, it works correctly if I select Chrome as browser. However if I chose Safari it does not fetch the user on the embedded browser window but it does when I then tap "open in browser".

**Comment by IsraelOrtuno** [comment]
I had this issue too, seems like fixed using:

```ts
  supabase: {
    clientOptions: {
      auth: {
        flowType: 'implicit',
      },
    },
  },
```
