### ISSUE TITLE
Avoid WARNING about missing .env

### ISSUE THREAD

**Issue by kleinpetr** [nuxt-modules/supabase#214]
Is there any option to avoid this WARNINGS?

![image](https://github.com/nuxt-modules/supabase/assets/17269309/7861af91-f09b-41de-9130-a8c4f57bf049)

Since I prefer registering credentials directly in the nuxt.config via runtime config like this

![image](https://github.com/nuxt-modules/supabase/assets/17269309/fda15d9b-379a-4b18-8d97-f35f079614dd)

I don't use .env for the dev environment, so I would like to hide this warning :pray: 
Thanks for help

**Comment by larbish** [comment]
Resolved by #281
