### ISSUE TITLE
Supabase API calls stopped working 

### ISSUE THREAD

**Issue by fdarkaou** [nuxt-modules/supabase#220]
Hi all,

Have been facing a pretty weird issue in with my application lately. I have supabase setup and all used to work completely fine. But suddenly API calls to tables stopped working. I can still generate a OTP to log in, session auth works as well. But all custom API calls to my tables and signOut do not work anymore. 

The weirdest thing is that I am not even getting any errors at all! I am working in a local environment, and have no logs in the browser, no logs on server side on my terminal, and also no logs on Supabase. Meaning the API call is not even received by Supabase. 

Another weird thing is that, if I remove my .nuxt and node_modules folder, do a re-install of everything, then for a minute or two it works fine, the API calls work correctly and I get data back from Supabase. But after one/two minutes, same thing all over again.

Anyone got any idea why this could be? It's super weird, especially that I'm not receiving any error messages anywhere that could help me troubleshooting. 

### Version
"@nuxtjs/supabase": "^0.3.8
"nuxt": "^3.6.2",

**Comment by CptJJ** [comment]
Was having the exact same issue, checkout my fork found here should be a drop in replacement with some minor refactoring of the getSupabaseUser.

https://github.com/nuxt-modules/supabase/issues/209

both the overrides and resolutions work around did not work for me.

**Comment by larbish** [comment]
Are you still facing this issue with the latest version ? Here is the [changelog](https://github.com/nuxt-modules/supabase/releases/tag/v1.0.1) with breaking changes.

**Comment by fdarkaou** [comment]
Thanks, the resolutions method got it working for me. 


> Hey, I've been struggling with this exact problem the past few hours now. Tried everything, the calls just get stuck when I try to call either signOut or getSession. It just seems to never get past the "await supabase.auth.[function]" stage:
> 
> ```
> export const signOut = async () => {
>   const supabase = useSupabaseAuthClient<Database>();
> 
>   const { error } = await supabase.auth.signOut();
>   
>   // It never reaches here and no request is sent in the network tab
> 
>   if (error) {
>     console.log(error);
>     return false;
>   }
> 
>   return true;
> };
> 
> export const getSession = async () => {
>   const supabase = useSupabaseAuthClient<Database>();
>   const { data, error } = await supabase.auth.getSession();  
>   
>   // It never reaches here and no request is sent in the network tab
> 
>   const { session } = data;
> 
>   return { session, error };
> };
> ```
> 
> I just looked through [this thread](https://github.com/nuxt-modules/supabase/issues/207), and once I added this to my package.json, it started working:
> 
> ```
>   "overrides": {
>     "@supabase/supabase-js": "2.31.0"
>   },
> ```
> 
> This was another solution that also worked for me (I use Yarn), but the recommended is using the overrides above:
> 
> ```
>   "resolutions": {
>     "@supabase/gotrue-js": "2.43.1"
>   },
> ```

**Comment by fdarkaou** [comment]
> Are you still facing this issue with the latest version ? Here is the [changelog](https://github.com/nuxt-modules/supabase/releases/tag/v1.0.1) with breaking changes.

Got it working using the solution mentioned above, will have a look at the latest version this weekend and come back to see if it works or not!

**Comment by fdarkaou** [comment]
> Are you still facing this issue with the latest version ? Here is the [changelog](https://github.com/nuxt-modules/supabase/releases/tag/v1.0.1) with breaking changes.

thanks larbish, this new version fixed it!!  appreciate your work on this🙏🏽

**Comment by lammerfalcon** [comment]
i have the same issue at 1.1.3 v.

**Comment by arthurmeb** [comment]
Facing this issue currently, any recommended fix?

**Comment by arthurmeb** [comment]
> Are you still facing this issue with the latest version ? Here is the [changelog](https://github.com/nuxt-modules/supabase/releases/tag/v1.0.1) with breaking changes.

Still facing this issue!

**Comment by jacob-restart** [comment]
Facing this issue myself too!

**Comment by ashikjs** [comment]
Still facing this issue!

**Comment by SAGAR-TAMANG** [comment]
Facing the issue as well. Stuck.
