### ISSUE TITLE
Getting 404 /login not found

### ISSUE THREAD

**Issue by dustin-we** [nuxt-modules/supabase#224]
### Version
@nuxtjs/supabase: v1.0.0
nuxt: 3.6.5

### Reproduction Link
[Here you can find my test repo](https://github.com/dustin-we/nuxt-supabase-bug-v1)

### Steps to reproduce
Clone the repository, or create a new Nuxt project and add @nuxtjs/supabase to it.

Run the dev server:
`npm run dev`

### What is Expected?
Your Nuxt project runs and shows a page according to the route you visited.

### What is actually happening?
The dev server shows the default Nuxt 404 page, stating that the route '/login' cannot be found. If you were to click on 'Go back home', it would display the page on '/' for a moment, but go back to '/login'.

To add to this:
If I install a previous verison of @nuxtjs/supabase, for example v0.3.8, it works as intended.

**Comment by dietler** [comment]
Same thing happening to me with the upgrade to 1.0.0

**Comment by CareTiger** [comment]
same here

**Comment by dustin-we** [comment]
Update: Not a bug, I just didn't read the breaking changes for v1.0.0 well enough.

In the [Release](https://github.com/nuxt-modules/supabase/releases) it states that:

> redirect option is enable by default, follow this [guide](https://supabase.nuxtjs.org/authentication) to update your app

If you follow the guide mentioned above, it works. This seems to be needed for a new Auth flow by Supabase and is therefore enabled by default, so the smart choice would probably be to implement the /login and /confirm. 

You could also disable it, you can find the option [here](https://supabase.nuxtjs.org/get-started#redirect)

**Comment by larbish** [comment]
Indeed, if you want to set your login form on the `/` route, you just have to set `redirectOptions.login: '/'` in your configs. You can also disable the all behaviour and set `redirect: false`.
