### ISSUE TITLE
1.0.1 version breaks app and redirects to /login automatically when not specified in nuxt.config

### ISSUE THREAD

**Issue by onurusluca** [nuxt-modules/supabase#227]
@nuxtjs/supabase: 1.0.1
nuxt: 3.6.5

I am asking this because I know there will be people who didn't read the[ release notes](https://github.com/nuxt-modules/supabase/releases/tag/v1.0.1) and wonder why their app redirects to /login.

> redirect option is enable by default, follow this [guide](https://supabase.nuxtjs.org/authentication) to update your app

If not explicitly set in nuxt.config.ts, nuxt supabase overrides the whole middleware and nuxt, and redirects to /login when not logged it.
For example if not set like this, redirect is `/login` by default.
```
  supabase: {
    redirectOptions: {
      login: "/signIn",
    },
  },
```

Nuxt already has a [middleware ](https://nuxt.com/docs/migration/plugins-and-middleware#route-middleware)for this. 
```
export default defineNuxtRouteMiddleware((to, _from) => {
  const user = useSupabaseUser();

  if (!user.value) {
    return navigateTo("/signIn");
  }
});
```

This would be inconvenient for the people who are not using nuxt auth as well.
What is the reason to add a redirect that just overrides everything? 
Why is it enabled by default? @larbish

**Comment by 1bye** [comment]
I'm currently using middleware for validation, which is why I disabled the `redirect` feature. However, I still require the `callback` field for OAuth. Do you have any idea?

**Comment by larbish** [comment]
I've made the choice to enable it by default to make the module more "plug & play". The first section in the documentation after the `get-started` is explaining the auth  / redirect process, it's hard to miss it. The redirect is just a middleware under the hood and you can easily allow "public" route with the [exclude](https://supabase.nuxtjs.org/get-started#redirectoptions) option. I think it is a good DX but if too many people are complaining about it, I could change.

@1bye You can just create a `callback` page and set your redirect url to it when calling `auth` methods from the client.

**Comment by onurusluca** [comment]
@larbish Thanks for the reply. I can't say I like it especially because not everyone is using supa auth.
Btw, have you tested this on Firefox?

With the below configs, on Chrome it works as expected but on Firefox, it redirects to /signIn even after signing in.
```
  supabase: {
    redirectOptions: {
      // If not specified, the default is login, so it will break the nuxt middleware auth flow
      login: "/signIn",
      callback: "/confirm",
      exclude: ["/unprotected", "/public/*"],
    },
  },
```

**Comment by Aietes** [comment]
@1bye The `callback` in `redirectOptions` is NOT determining your redirect URL, you actually set that in your respective login function code via the `redirectTo` option, like so:

```ts
const signInWithOAuth = async () => {
  const { error } = await supabase.auth.signInWithOAuth({
    provider: 'github',
    options: {
      redirectTo: 'https://<your.domain>/confirm',
    },
  })
  if (error) console.log(error)
} 
```
Make sure that the URL you use here is explicitly configured in your Supabase `Authentication -> URL Configuration` settings, otherwise the redirect default's to your site URL.

The `callback` option is used when `redirect: true` to take care of a couple of other settings that are important for auth to work reliably:

1. It is very important to make sure that the redirect route right after login works without any server-side rendering. When using the module's redirect default, the callback route (`/confirm` by default) is excluded from SSR by setting a route rule with `{ssr: false}`. If you disable the modules redirect, make sure to add such a route rule for your callback URL manually in your `nuxt.config.ts`, something like:

```ts
export default defineNuxtConfig({
  nitro: {
    routeRules: {
      '/confirm': { ssr: false },
    },
  },
})
```

2. Under the hood `redirect:true` adds a global middleware to check for auth. Here the `callback` option is ensuring that the middleware does not check for authentication on that route. During the authentication process the session is created on the confirm page, so there is no session yet when you navigate to it, therefore the middleware would always redirect back to the login page. If you use your own middleware, ensure that you take care of that.

Overall, for most people it should make sense to use the default `redirect: true` module option, so that all the things above are taken care of automatically.

**Comment by Aietes** [comment]
@onurusluca Under the hood the module adds a global middleware when the option `redirect` is enabled. While you are right that it seems easy enough to add a middleware yourself, there a number of details that must be taken care of for both the authentication and the middleware to work reliably, as described above. Many users might miss those details.

If you don't want to use authentication, it's easy enough to set `redirect:false` in the module options, but I think many people are using Supabase specifically for it's authentication and related RLS features.

**Comment by Blurpish** [comment]
Why do I get redirected every time I reload the page even if already authenticated?

**Comment by onurusluca** [comment]
@Aietes Thanks for the reply.
As @Blurpish said, supabase forcibly redirects to login page even if logged in. I could only reproduce this on Firefox for now. Are you able to reproduce this bug?

**Comment by Aietes** [comment]
I just tested the module playground on Firefox, and reloading the page does not redirect when logged in. In a clean setup I can't reproduce this bug.

In your project where this occurs, are you still using your own middleware? Do you use the module with `redirect: true`? If the module middleware is used, the only reason to get forwarded to the login page is when the session didn't get initialized properly. This could point to an issue with the `/confirm` page, where the session is created.

Top determine the cause of the issue, can you provide a minimal minimal reproduction using one of the starter templates?

👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
👉 https://codesandbox.io/s/github/nuxt/starter/v3-codesandbox

**Comment by 1bye** [comment]
@Aietes Thanks for reply.
So I configured `Authentication -> URL Configuration settings`, but when sign in using github or google, it redirects me to root url of app with query: `/?code=4745a54c-4387-4469-aa27-7df6ec09e2cc`.
```js
// Current code of auth
const signInGithub = async () => {
  const { error } = await client.auth.signInWithOAuth({
    provider: 'github',
    options: {
      redirectTo: '/confirm',
    },
  })
  ...
} 
```
Do you have any idea?

**Comment by 1bye** [comment]
I successfully solved my issue by making the following changes: 
I replaced `redirectTo: '/confirm'`, with the fullpath URL and performed a `nuxi cleanup`. 
Thanks @Aietes @larbish

**Comment by Aietes** [comment]
The redirect you are experiencing is performed by Supabase. Supabase does require fully qualified addresses, since it doesn't know your app and routes. Change you code to use the full redirect URL in the function call, and the the same full URL in the Supabase settings:

```ts
// Current code of auth
const signInGithub = async () => {
  const { error } = await client.auth.signInWithOAuth({
    provider: 'github',
    options: {
      redirectTo: 'https://localhost:3000/confirm',
    },
  })
  ...
} 
```

**Comment by Blurpish** [comment]
@Aietes 
Here is a template the reproduces my issue :
https://stackblitz.com/edit/github-urzwda

**Comment by Aietes** [comment]
@Blurpish When you are using sign-in with e-mail and password, no callback is required. The session is directly created. Therefore no need to navigate to the callback page. Instead, you can just navigate to the page you want authenticated users to go to:

```ts
<script lang="ts" setup>
const supabase = useSupabaseClient();

const email = ref();
const password = ref();

async function login() {
  const { error } = await supabase.auth.signInWithPassword({
    email: email.value,
    password: password.value,
  });
  if (error) {
    console.log(error)
  } else {
    return navigateTo('/user')
  }
}
</script>
```
I tested this, and it works fine in Firefox, Chrome and Safari, including refreshing pages.

**Comment by onurusluca** [comment]
> I just tested the module playground on Firefox, and reloading the page does not redirect when logged in. In a clean setup I can't reproduce this bug.
> 
> In your project where this occurs, are you still using your own middleware? Do you use the module with `redirect: true`? If the module middleware is used, the only reason to get forwarded to the login page is when the session didn't get initialized properly. This could point to an issue with the `/confirm` page, where the session is created.
> 
> To determine the cause of the issue, can you provide a minimal minimal reproduction using one of the starter templates?
> 
> 👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz 👉 https://codesandbox.io/s/github/nuxt/starter/v3-codesandbox

@Aietes Thanks for the reply. My bad for not providing a reproduction. 
I realized the after restarting my computer, the problem is gone. I guess it has something to do with Nitro's or Nuxt's cache?

Just to clarify, I wasn't using Nuxt's middleware. Redirect wasn't specified. 
It works fine now. 

My question is answered, feel free to close this thread whenever other's problems are solved.

**Comment by Aietes** [comment]
@onurusluca I'm glad that things work now! 👍🏻

**Comment by Aietes** [comment]
@Blurpish I created a new issue #236 for the problem, to track is properly. A respective PR #237 to fix it has been created.

**Comment by R0N1n-dev** [comment]
Problem for me as well. cannot get past login page.

**Comment by Jeet-Metapercept** [comment]
Same Issue.

**Comment by onurusluca** [comment]
I see the docs are fixed and it is easy to understand so I am closing this issue.

**Comment by mbalves1** [comment]
apparently supabase: { redirect: false } has been discontinued, what alternative?
