### ISSUE TITLE
useSupabaseUser() has type any?

### ISSUE THREAD

**Issue by CptJJ** [nuxt-modules/supabase#228]
useSupabaseUser() has type any and all logic along the lines of if (user) {} has broken.

Is it no longer advised to use this composable?

### Version
@nuxtjs/supabase: 1.0.1
nuxt: 3.6.2

**Comment by larbish** [comment]
<img width="480" alt="Screenshot 2023-08-04 at 08 29 35" src="https://github.com/nuxt-modules/supabase/assets/7290030/3983d32a-ec4a-432f-9254-fc61c0353e94">

Not sure to understand your issue. `useSupabaseUser()`is typed and  it's returning a ref. Your if condition should be `if (user.value) {}`

**Comment by emilioschepis** [comment]
Hey @larbish,

I am also seeing this in a newly created project, the `.d.ts` file might not be exporting the correct type.

<img width="649" alt="Screenshot 2023-08-04 at 15 12 11" src="https://github.com/nuxt-modules/supabase/assets/16031715/dbf8b801-7983-4349-9fd6-ac4596a63cd8">

Also seeing it here: https://unpkg.com/browse/@nuxtjs/supabase@1.0.1/dist/runtime/composables/useSupabaseUser.d.ts

Thanks!

**Comment by CptJJ** [comment]
@larbish pinging just incase you guys dont get notified for closed issues. Seems like this wasnt just me?

**Comment by LouisHaftmann** [comment]
it's any for me too :(

**Comment by AlbertBrand** [comment]
Hi, I did some checking yesterday and it seems to be a problem since v1.0.0-0. I haven't figured out where this goes wrong, it might be an issue in configuration, or in the `unbuild` dep or even a lower one. I did find a workaround, which I added in #254.

**Comment by AlbertBrand** [comment]
This is not the only problem, the plugin export gets typed as `any` as well which is probably bad as well. There is a unanswered issue in `nuxt/module-builder` which is relevant: https://github.com/nuxt/module-builder/issues/95

**Comment by AlbertBrand** [comment]
@larbish Please reopen this issue as this is important to fix.
