### ISSUE TITLE
useSupabaseUser() returns null on page load after oauth redirect

### ISSUE THREAD

**Issue by nddr** [nuxt-modules/supabase#234]
### Version
@nuxtjs/supabase: v1.0.2
nuxt: v3.6.5

### Steps to reproduce
This happens when logging in with both Discord and Google OAuth.
- Sign in with OAuth provider (Redirect to provider)
- Authorize (Redirect back to app)
- Check useSupabaseUser

### What is Expected?
Before v1.0.0 useSupabaseUser would return the logged in user.

### What is actually happening?
When being redirected back from authorization, useSupabaseUser returns null on page load.

My Nuxt/Supabase config
```
  supabase: {
    redirectOptions: {
      login: '/',
      callback: '/',
      exclude: ['/agents', ... '/oauth'],
    },
  },
```

**Comment by Aietes** [comment]
Try a separate login and callback page. Trying to handle everything on one page can lead to problems.

**Comment by nddr** [comment]
Thanks @Aietes

**Comment by nddr** [comment]
@Aietes, interesting find, I didn't have to use the `redirectTo:` option for it to work. I only needed to change the `callback` in the redirectOptions to '/confirm'. I also don't need a confirm page.
