### ISSUE TITLE
The changelog markdown file in the root of the repo is missing version 1

### ISSUE THREAD

**Issue by Siilwyn** [nuxt-modules/supabase#261]
The latest version is missing, seems like the file has not been updated since version 0.3.0.

**Comment by larbish** [comment]
Thanks. i've removed it and update the readme link to http://supabase.nuxtjs.org/changelog

**Comment by Siilwyn** [comment]
Thanks for the reply, I would like to advocate for a markdown file though! It's accessible from my editor (offline even), and easy to parse when using tools to inspect changelog changes.

**Comment by larbish** [comment]
I'll regenerate it for the next version.

**Comment by Siilwyn** [comment]
Awesome! :clap:
