### ISSUE TITLE
SSR Doesn't work in my app with Supabase

### ISSUE THREAD

**Issue by razmatinyan** [nuxt-modules/supabase#265]
### Describe the problem
I have an issue with my Nuxt 3 App. It is not rendering is SSR mode. When I look at page in **`"View page source"`** mode, it is not rendered in SSR. In main `"__nuxt"` block I got empty `<div id="__nuxt"></div>` .

### Reproduction
https://stackblitz.com/edit/nuxt-shortener-url?file=app.vue,app.config.ts

### Notes
I left `example.env` file in reproduction, with my Supabase datas. So please don't steal it :)

P.S. Problem comes from Supabase. When I fully disable the Supabase the website starts to render in SSR correctly, but when I enable it, i get only empty `__nuxt` block.

**Comment by razmatinyan** [comment]
_Update!_

I set the `redirect` option to `false` and it fixed my issue.

Closing.

**Comment by HC-miss** [comment]
After locating it for a long time, I found that it was a problem with this module. This problem still exists, but it can be solved by using `redirect=false`. I don’t know the logic behind the problem.

**Comment by HC-miss** [comment]
After locating it for a long time, I found that it was a problem with this module. This problem still exists, but it can be solved by using `redirect=false`. I don’t know the logic behind the problem.
