### ISSUE TITLE
No overload matches this call

### ISSUE THREAD

**Issue by mathieunicolas** [nuxt-modules/supabase#279]
Hello there, 

I'm not very skilled in using classes and types, so I'm quite learning.
Currently with latest nuxt and nuxt-supabase modules.

I'm trying to setup basic stuff and I can't fix a TS error with this code : 
```ts
export class Chapter {
  id: string;
  text: string;

  constructor(id: string, text: string) {
    this.id = id;
    this.text = text;
  }

  async insert() {
    const supabase = useSupabaseClient()
    const res = await supabase
    .from('chapters')
    .insert({
      text: this.text
    })
  }
}
```

I have the following TS "error" : 
<img width="970" alt="Screenshot 2023-09-28 at 00 55 32" src="https://github.com/nuxt-modules/supabase/assets/65437872/263e016b-f3d3-4797-a790-17c897698fb3">

Everything works fine and the chapter is eventually created in the database, but I don't know how I can fix the warning.
Any help ?

Thanks !

**Comment by Dmytro-Tihunov** [comment]
Same here (

**Comment by mathieunicolas** [comment]
It works like a charm. Thanks a lot !!!
