### ISSUE TITLE
`sb-access-token` and `sb-refresh-token` cookie doesn't get set on login

### ISSUE THREAD

**Issue by guarenty** [nuxt-modules/supabase#300]
Okay, i am going crazy with this one. It took me a whole lot of time to figure the underlying problem out - at least I think that this is the problem, or better I hope.

### Version
@nuxtjs/supabase: v1.1.3
nuxt: v3.8.0

### Reproduction Link

https://github.com/guarenty/supabase-nuxt-test
(nothing special, just an 

### Steps to reproduce

1. `npm install`
2. Add SUPABASE_URL and SUPABASE_KEY to your .env file
3. npm run dev
4. navigate to localhost:3000 (you should get logged in and the response get displayed)

### What is Expected?

The `sb-access-token` and `sb-refresh-token` cookie should be set.

### What is actually happening?

They doesn't get set.

### Problems related to this, at least I think so.

I can't use `await serverSupabaseUser(event)` in any server route, because there are no cookies set. I get the following error message: `invalid claim: missing sub claim`. I think it is the same Error mentioned here #238

Another issue is that you get redirected to your '/login' page even when you are already logged in. See #264 

### What I tried

I tried the same with an older Project (@nuxtjs/supabase: v0.3.8) and the cookies get set and everything works fine. Even if I started the dev server of my new project after that everything works fine when using the same internet tab (so the cookies are still there). So my conclusion here is that this is the same problem as in the mentioned issues and maybe in some more.

### Conclusion

If I understand this correctly this issue breaks a lot of things. I am trying to look in into the `supabase.auth.signInWithPassword()` function and maybe I can figure something out.

Thanks for your time and help!

### Edit
@truesteps mentioned that this issue only popped up on safari for him.

**Comment by guarenty** [comment]
Okay, I wrote a little script that listen for auth changes and then set or remove the cookies. Now the mentioned Problems are resolved. But I think [https://github.com/nuxt-modules/supabase/blob/main/src/runtime/plugins/supabase.client.ts](supabase.client.ts) should do it natively. 
One difference between this and my code is that I do set the 'secure' cookie option to false, otherwise it doesn't work. Even when I do not understand why, because it is mentioned in the documentation that 'secure' should work on localhost.

**Comment by rogrile** [comment]
@guarenty can you share the changes that helped you make this work?

**Comment by guarenty** [comment]
@rogrile Yes, I can. But keep in mind that is just a fix from me, so no idea if it is acceptable. And I may be changing it later on.

I added the following to 'app.vue':

``` vue app.vue
<script setup lang="ts">

/**
 * Handle Auth Cookies
 */
const supabase = useSupabaseClient()

// get cookie options
const config = useRuntimeConfig().public.supabase;
const { url, key, cookieName, cookieOptions, clientOptions } = config;

const accessToken = useCookie('sb-access-token', {
  maxAge: cookieOptions.maxAge,
  path: "/",
  sameSite: <boolean | "lax" | "strict" | "none" | undefined>cookieOptions.sameSite,

  // secure: cookieOptions.secure // if this is enabled it doesn't work anymore
})

const refreshToken = useCookie('sb-refresh-token', {
  maxAge: cookieOptions.maxAge,
  path: "/",
  sameSite: <boolean | "lax" | "strict" | "none" | undefined>cookieOptions.sameSite,
})

// listen for auth changes, set/delete cookies
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'SIGNED_OUT') {
    // delete cookies on sign out
    accessToken.value = null
    refreshToken.value = null
  } else if (event === 'SIGNED_IN' || event === 'TOKEN_REFRESHED') {
    // set cookies on sign in
    accessToken.value = session?.access_token
    refreshToken.value = session?.refresh_token
  }
})

</script>
```

**Comment by truesteps** [comment]
@guarenty this fixed the issue for me, altho, furthermore I had to add `headers: useRequestHeaders(['cookie'])` int oevery $fetch request I made to the backend where i use `await serverSupabaseUser(event)`

**Comment by truesteps** [comment]
> @guarenty thank you so much! this fixed the issue for me, altho, furthermore I had to add `headers: useRequestHeaders(['cookie'])` int oevery $fetch request I made to the backend where i use `await serverSupabaseUser(event)`

Also, this issue popped up only on safari for me... On chrome and firefox it worked splendidly

**Comment by guarenty** [comment]
> 
> Also, this issue popped up only on safari for me... On chrome and firefox it worked splendidly

You mean the whole issue with the cookies or just your additional fix with the headers?¿

**Comment by truesteps** [comment]
> > Also, this issue popped up only on safari for me... On chrome and firefox it worked splendidly
> 
> You mean the whole issue with the cookies or just your additional fix with the headers?¿

Sorry for the unclearness, the whole cookie issue popped up only on safari

**Comment by alexgrozav** [comment]
Spent hours trying to figure out why my requests wont go through before I realized I'm on Safari. Thans for the fix @guarenty.

Can we get this into the next release please? 🙏

**Comment by larbish** [comment]
Seems like Safari is not accepting `secure` cookies on `localhost`. So for users that want to use Safari for local development, you can fix this bug by setting `cookieOptions.secure` to `false` in your `nuxt.config.ts` file:

```ts
export default defineNuxtConfig({
  supabase: {
    cookieOptions: {
      secure: process.env.NODE_ENV === 'production',
    }
})
```

**Comment by truesteps** [comment]
@larbish is this completed with 1.1.4. or should we expect a new release?

**Comment by larbish** [comment]
@truesteps Doesn't my proposal resolve your issue?

**Comment by truesteps** [comment]
@larbish my bad, I didn't read up, only that it's been resolved, let me try and let me get back to you after

**Comment by truesteps** [comment]
@larbish tested and it fixed it for me, many thanks :)
