### ISSUE TITLE
Possible or necessary modifications after the release of `@supabase/ssr`

### ISSUE THREAD

**Issue by MAXOUXAX** [nuxt-modules/supabase#301]
I'd like this issue to be used as a forum for discussing necessary or possible modifications after the release of `@supabase/ssr`, whose guide is [available here](https://supabase.com/docs/guides/auth/server-side/creating-a-client)

Can/should changes be made to this module?
If so, which ones?
What are the implications?

**Comment by felixgabler** [comment]
I would also really like to know. In the future, auth helpers will probably be deprecated but there are many other useful parts in this Nuxt module so I guess one can just make it sit atop `@supabase/ssr` by replacing `createClient` with `createServerClient` from `@supabase/ssr` (and in `supabase.client.ts` maybe rather with `createBrowserClient`)?

**Comment by jfoucher** [comment]
I just submitted a PR that fixes an issue when using nuxt SSR with docker-compose. Other than that, everything seems to work fine. This project seems more or less abandoned, though... Maybe @larbish or @Atinux can clarify?

**Comment by Atinux** [comment]
It is not abandoned, just that the maintainer also work on other stuff, I commented on your PR :)

From what I see, the module works well anyway, but it could be nice to update for the `@supabase/ssr`.

I believe it could be updated on:
- https://github.com/nuxt-modules/supabase/blob/main/src/runtime/plugins/supabase.server.ts
- https://github.com/nuxt-modules/supabase/blob/main/src/runtime/server/services/serverSupabaseClient.ts

PR is more than welcome, this is a free and open community project, I will do my best to review it ❤️
