### ISSUE TITLE
Routing Freezes After Installing Supabase Module in Nuxt 3

### ISSUE THREAD

**Issue by bjorne84** [nuxt-modules/supabase#318]
"devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/supabase": "^1.1.4",
    "nuxt": "^3.8.2",
    "vue": "^3.3.10",
    "vue-router": "^4.2.5"
  }

## Description:
After installing the Supabase module in a Nuxt 3 application, the routing functionality seems to freeze. Specifically, the application only shows the content from localhost/login and does not navigate to other routes. This issue does not occur until the Supabase module is added to the project.

## Steps to Reproduce:
Clone this project https://github.com/bjorne84/supabaseNuxt3Test 
**or** 
Create a new Nuxt 3 project with basic pages and a layout with a header component. Verify that routing between pages works as expected.
Install the Supabase module using [specific installation steps or commands].
Observe that the routing no longer functions correctly; the application is stuck on the localhost/login route.

## Expected Behavior:
Navigation between different routes should work seamlessly, irrespective of whether the Supabase module is installed.

## Actual Behavior:
Once the Supabase module is installed, the application's routing freezes, and only the localhost/login route is accessible.

## Additional Information:
No significant errors or warnings appear in the console or server logs, making it difficult to pinpoint the exact cause.
The problem persists across different browsers and restarts of the development server.

**Comment by owljackob** [comment]
Did you set the `redirect` option to `false`?

**Comment by bjorne84** [comment]
Thanks, Setting the redirect option to false fixed the routing issue.

**Comment by jay-szczerkowski** [comment]
Struggling with the same problem on my Nuxt3 + Supabase app
Seems like your solution fixed the issue, thank you!
