### ISSUE TITLE
Auth not set on server side with link (magic link) login

### ISSUE THREAD

**Issue by mwohlan** [nuxt-modules/supabase#32]
### Version
@nuxtjs/supabase: v0.1.9
nuxt: v3.0.0-rc.1

### Steps to reproduce

Set up a login form using the just the email to receive a magic link
```js
const { session, error } = await client.auth.signIn({ email: email.value })
```

Use a middleware like this
```js
export default defineNuxtRouteMiddleware((to) => {
  const user = useSupabaseUser()
  if (!(user.value))
    return navigateTo({ name: 'login', query: { redirect: to.path } })
})
```

### What is Expected?

The user should be set on the server side.

### What is actually happening?

The token on the server side plugin is null:

```js
export default defineNuxtPlugin(async () => {
  const user = useSupabaseUser();
  const client = useSupabaseClient();
  const token = useSupabaseToken();
  if (!token.value) {
    return;
  }
  const { user: supabaseUser, error } = await client.auth.api.getUser(token.value);
  user.value = error ? null : supabaseUser;
});
```

Therefore the middleware redirects the user to the login and the user only becomes available after the
middleware has run, leaving the user on the login page. A fix would involve watching the user, but thats still leads to the login page shortly showing up before the user is redirected again.

This issue is linked to [#28](https://github.com/nuxt-community/supabase-module/issues/28) but singles out the ssr issue when using magic links

**Comment by larbish** [comment]
I have no choice, the Supabase `onAuthStateChange` event is sent on client side. Once the event is received, it shares the data between server and client. Until then, the server is not synced. 😞

Indeed, you can watch on the user and redirect once it has been set. To avoid display login form you can do something like this: 
```
<template>
  <div v-if="user">
    Redirecting...
  </div>
  <LoginCard v-else />
</template>

<script setup>
const user = useSupabaseUser()

watchEffect(() => {
  if (user.value) {
    navigateTo('/')
  }
})

</script>
```

**Comment by nosizejosh** [comment]
Hello @larbish can you please explain what you mean with the magic link solution? A sample codebase for both signup and signin will be great. Will there be a more permanent solution or this is it?

**Comment by larbish** [comment]
Hey @nosizejosh, that's a way I found to avoid the display of the login form highlited by @mwohlan. That was just a proposition.

**Comment by nosizejosh** [comment]
@larbish from this tutorial https://vueschool.io/articles/vuejs-tutorials/use-supabase-auth-with-vue-js-3/ and this snippet

```
// setup auth state listener
supabase.auth.onAuthStateChange((event, session) => {
  // the "event" is a string indicating what trigger the state change (ie. SIGN_IN, SIGN_OUT, etc)
  // the session contains info about the current session most importanly the user dat
  const { user } = useAuthUser();

  // if the user exists in the session we're logged in
  // and we can set our user reactive ref
  user.value = session?.user || null;
});
```
does this module create an auth state listener to be able to solve this issue?
if not, how can I integrate this for example in my codebase so auth state change can be monitored to solve this issue?
Thank you

**Comment by nosizejosh** [comment]
Thank you @larbish
