### ISSUE TITLE
MINOR: `<NuxtLayout />` component has not been used.

### ISSUE THREAD

**Issue by Arbust908** [nuxt-modules/supabase#328]
### Version
"@nuxtjs/supabase": "^1.1.6",
    "nuxt": "^3.9.3",
    "vue": "^3.4.14",
    "vue-router": "^4.2.5"

### Reproduction Link

[Reproduction](https://stackblitz.com/edit/github-yqlzeu?file=app.vue,pages%2Findex.vue,.env.example,.env,layouts%2Fdefault.vue,pages%2Flogin.vue)

### Steps to reproduce

- Start new nuxt
- Add `@nuxtjs/supabase` (Add .env with required variables and add module to `.config`)
- Get `[Vue Router warn]: No match found for location with path "/login"`
- Add `/pages/index.vue`, add `<NuxtLayout>` && `<NuxtPage>` to `app.vue` and add a `/layouts/default.vue`
- [Add '/login' from docs ](https://supabase.nuxtjs.org/authentication) 
- Get `[nuxt] Your project has layouts but the `<NuxtLayout />` component has not been used.`

### What is Expected?

I expect not to get an error when `layouts` and `<NuxtLayout />` are being correctly used.

### What is actually happening?

I get the `[nuxt] Your project has layouts but the `<NuxtLayout />` component has not been used.` error on the console. Still the layout gets applied

**Comment by selemondev** [comment]
Hey there @Arbust908 , this issue is related to Nuxt and not the `@nuxtjs/supabase` module. The issue is currently being tracked [here](https://github.com/nuxt/nuxt/issues/25912)
