### ISSUE TITLE
nuxt.config.ts type bug

### ISSUE THREAD

**Issue by KenZync** [nuxt-modules/supabase#337]
### Version
@nuxtjs/supabase: 1.1.7
nuxt: 3.11.1

### Reproduction Link
-

### Steps to reproduce
-init new nuxt project
-install supabase
-add config

### What is Expected?
should be like this, no error , this is old version nuxt 3.8.2, supabase 1.1.4
![image](https://github.com/nuxt-modules/supabase/assets/18224778/b3d6782c-e77f-45a5-869f-0fc25bb1fc29)

### What is actually happening?
it is throwing error for some reason
nuxt.config.ts
```// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    '@nuxt/ui',
    '@nuxtjs/supabase'
  ],
  supabase: {
    redirectOptions: {
      login: '/',
      callback: '/confirm'
    }
  },
})
```

![image](https://github.com/nuxt-modules/supabase/assets/18224778/5e49225c-c457-4887-86cb-296aedeae177)

**Comment by KenZync** [comment]
add this into tsconfig.json fix the bug but should it not have to be added?
```"compilerOptions": {
"moduleResolution": "node",
}```

**Comment by selemondev** [comment]
Upgrade `nuxt` and `@nuxtjs/supabase` to the latest version and everything will work fine without you having to set the `"moduleResolution"` to `"node"` in the tsconfig.json file.

**Comment by pascalwengerter** [comment]
@KenZync is this still a problem? I think I've come across this, but seems like something that's fixed by running `pnpm postinstall` (so Nuxt re-creates its types) and potentially re-starting VsCode (since it somethings gets "stuck" on such type errors, at least in my experience)

**Comment by KenZync** [comment]
I haven't checked new version since I already fixed with my own method. Thank you for your suggestion

> @KenZync is this still a problem? I think I've come across this, but seems like something that's fixed by running `pnpm postinstall` (so Nuxt re-creates its types) and potentially re-starting VsCode (since it somethings gets "stuck" on such type errors, at least in my experience)
