### ISSUE TITLE
Error when using oauth with provider linkedin_oidc - Error getting user profile from external provider

### ISSUE THREAD

**Issue by omerhochman** [nuxt-modules/supabase#351]
### Version
@nuxtjs/supabase: v1.2.0
nuxt: v3.6.5

When using signInWithOAuth with linkedin_oidc

```
const client = useSupabaseClient()
const result = await client.auth.signInWithOAuth({
    provider: 'linkedin_oidc',
    options: {
        redirectTo: '...'
    }
})
```

It redirects back to the redirectTo URL with the following query params:
`error=server_error&error_code=500&error_description=Error+getting+user+profile+from+external+provider#error=server_error&error_code=500&error_description=Error+getting+user+profile+from+external+provider`

When checking the Auth logs in the Supabase platform I found this error:
`error: oidc: id token issued by a different provider, expected \"https://www.linkedin.com\" got \"https://www.linkedin.com/oauth\"","level":"error","method":"GET","msg":"500: Error getting user profile from external provider`

**Comment by omerhochman** [comment]
I found [supabase/auth](https://github.com/supabase/auth/issues/1533) repo to be the more relevant place for this issue so I've opened the same one there.

**Comment by Drew-Macgibbon** [comment]
I was facing the same issue with `1.20`, seems to be working fine with `1.21` , must have been fixed upstream.
