### ISSUE TITLE
Dynamic routes break login authentication check

### ISSUE THREAD

**Issue by felixranesberger** [nuxt-modules/supabase#359]
When using dynamic routes using the pages directory `pages/editor/club-[group]/female` I get the login page. This is not expected since I'm logged into the site and all pages work except the page with the dynamic route.

I suspect it has something to do with this, but I have no clue how to fix it.

**Comment by andreasvirkus** [comment]
How did you end up excluding those pages? I have a similar issue with API routes

```ts
server/api/scan/[id].ts
```

And when I visit `/api/scan/19`, I get redirected to `/login`

**Comment by felixranesberger** [comment]
I think I actually never got it to work properly. I changed my dynamic route to a query parameter, because I could use this as well and moved on. I still have quite some problems with auth and (Vercel) ISR caching and thinking about moving the authentication to another library.
