### ISSUE TITLE
Error when signing out

### ISSUE THREAD

**Issue by newtondotcom** [nuxt-modules/supabase#367]
### Version
@nuxtjs/supabase: ^1.1.7
nuxt: ^3.11.1

### Reproduction Link
https://github.com/newtondotcom/mgrs

### Steps to reproduce
Just try to log in and log out and look at console

### What is Expected?
To log out user without issue

### What is actually happening?
Forbidden 403 error page saying : 
`"message":"No API key found in request","hint":"No `apikey` request header or url param was found."}`

I can't use `const supabaseAuth = useSupabaseAuthClient()` because it is not found

**Comment by larbish** [comment]
Can you have a try with the latest release? https://github.com/nuxt-modules/supabase/releases/tag/v1.3.1
