### ISSUE TITLE
Middleware not working well

### ISSUE THREAD

**Issue by QThans** [nuxt-modules/supabase#370]
I can get user by using `const { supabaseUser } = useSupabaseUser(supabase)`. However, the middleware is not working well, it redirects to '/login' every time.

**Comment by QThans** [comment]
after refresh, login status invalid, the middleware determines whether the login error occurred and jumps to the login page.

**Comment by caiotarifa** [comment]
Hello, @QThans.

Did you find a solution? I'm going through the same problem.

**Comment by QThans** [comment]
> caiotarifa

for me, caused by the wrong code for using `useSupabaseClient `.

**Comment by victor-ponamariov** [comment]
How did you solve it?

https://supabase.nuxtjs.org/usage/composables/usesupabaseuser

This middleware returns null for the user. If I remove the middleware, I can access user vis `useSupabaseUser` in other places
