### ISSUE TITLE
Need to update to new supabase-js version for a bug fix

### ISSUE THREAD

**Issue by onurusluca** [nuxt-modules/supabase#442]
Hi sorry for not opening a PR as I don't know the procedure when updating packages.

With the 1.4.4 that uses an older supabase-js version, user gets logged out automatically. This bug is fixed with the new authjs version which was merged to supabase-js two days ago.
 
Need a quick version update on supabase-js package to: 
https://github.com/supabase/supabase-js/releases/tag/v2.47.7

Because of this bug:
https://github.com/supabase/auth-js/issues/995

For this fix:
https://github.com/supabase/auth-js/pull/999

**Comment by urbansky** [comment]
I've the same issue and i thought the Server-Side-Rendering is broken. But the supabase-package is broken. Thanks!
The solution are in the comments of the supabase-package.

Use 'overrides' in your package.json to use the new version:

`  
"overrides": {
    "@supabase/auth-js": "2.66.1"
  },
`

see https://github.com/supabase/auth-js/issues/995#issuecomment-2540308860

**Comment by onurusluca** [comment]
> I've the same issue and i thought the Server-Side-Rendering is broken. But the supabase-package is broken. Thanks! The solution are in the comments of the supabase-package.
> 
> Use 'overrides' in your package.json to use the new version:
> 
> ` "overrides": { "@supabase/auth-js": "2.66.1" },`
> 
> The new version 2.67.1 is also OK
> 
> see [supabase/auth-js#995 (comment)](https://github.com/supabase/auth-js/issues/995#issuecomment-2540308860)

Yeah exactly. Currently using overrides as well but the package needs to be updated anyways.

**Comment by paranoidPhantom** [comment]
Also having my sb-db-auth-token cookie wiped on page refresh...

**Comment by larbish** [comment]
I've updated `supabase/supabase-js` to latest. Can you confirm it's fixed in  [1.4.5](https://github.com/nuxt-modules/supabase/releases/tag/v1.4.5) ?

**Comment by urbansky** [comment]
> I've updated `supabase/supabase-js` to latest. Can you confirm it's fixed in [1.4.5](https://github.com/nuxt-modules/supabase/releases/tag/v1.4.5) ?

Yes, it works in my project. Thanks for updating!

**Comment by onurusluca** [comment]
> I've updated `supabase/supabase-js` to latest. Can you confirm it's fixed in [1.4.5](https://github.com/nuxt-modules/supabase/releases/tag/v1.4.5) ?

Thank you!
