### ISSUE TITLE
Supplying env variables through runtime config?

### ISSUE THREAD

**Issue by marssantoso** [nuxt-modules/supabase#72]
Is it possible to supply the environment variables through runtime config instead of a `.env` file as mentioned in [the doc](https://supabase.nuxtjs.org/get-started#installation)?

Edit: I assume it's not possible due to the nature of this module (runs on build time)?

**Comment by larbish** [comment]
Hello @marssantoso, `process.env.xxxx` are just default values that can be overridden in your `nuxt.config.ts`:

```ts
import { defineNuxtConfig } from 'nuxt'
export default defineNuxtConfig({
  supabase: {
    url,    
    key,
    serviceKey,
    client,
    cookies
  }
}
```

Just be sure to not share this code publicly.
