### ISSUE TITLE
Reset password link

### ISSUE THREAD

**Issue by CareTiger** [nuxt-modules/supabase#74]
Hello everyone,

I am new to Supabase. I love the auth experience so far (compared to Firebase). what method do I call on the useSupabaseClient() to send the user a link to reset the password? 

Thank you so much

**Comment by madebyfabian** [comment]
Hey, since this is a wrapper module for @supabase/supabase-js for all of those questions refer to the supabase-js docs https://supabase.com/docs/reference/javascript/auth-api-resetpasswordforemail

Since this is not an issue, I think it can be closed
