### ISSUE TITLE
How do I use the service_key in an API call? 

### ISSUE THREAD

**Issue by phillipmohr** [nuxt-modules/supabase#79]
Hi, I'm trying to list all users and was told that it would work like this: https://supabase.com/docs/reference/javascript/auth-api-listusers

I tried:
1. Add `SUPABASE_SERVICE_ROLE_KEY` to .env
2. Call API 
```ts
import { serverSupabaseClient } from '#supabase/server'
export default defineEventHandler(async ({ event, req }) => {
    const supabase = serverSupabaseClient(event)
    const { data: users, error } = await supabase.auth.api.listUsers()

    if (error) {
        return error
    }

    return users
})
```

I receive "User not allowed", status 401. 

I'm not sure if this question belongs here, as I'm not sure if it's a nuxt/supabase thing I don't understand or if it has to do with supabase itself. As from my understanding, the `SUPABASE_SERVICE_ROLE_KEY` in the .env is automatically being used or do I need to do something else?

Thanks in advance

**Comment by phillipmohr** [comment]
got it working. I had to use `import { serverSupabaseServiceRole } from '#supabase/server'`

```ts
import { serverSupabaseServiceRole } from '#supabase/server'

export default defineEventHandler(async ({ event, req }) => {
    const supabase = serverSupabaseServiceRole(event)
    const { data: users, error } = await supabase.auth.api.listUsers()

    if (error) {
        return error
    }

    return users
})
```

**Comment by denishacquin** [comment]
> 

What naming did you end up using for the key in .env? When I use SUPABASE_SERVICE_ROLE_KEY it says `Missing SUPABASE_SERVICE_KEY in .env   `, event if I name it to SUPABASE_SERVICE_KEY.
