### ISSUE TITLE
In Netlify, function is calling "/api/_supabase/session" hundreds of times per second. Have over 13 million function calls for the endpoint in two days.

### ISSUE THREAD

**Issue by zkschmitz** [nuxt-modules/supabase#80]
### Version
@nuxtjs/supabase: v0.1.25
nuxt: 3.0.0-rc.11

### Reproduction Link
Private repository but happy to grant access to someone independently

### Steps to reproduce
Using the basic useSupabseClinet() and useSupabaseUser() functions throughout my code to reference the logged in user and the  supabase instance.

This started happening after moving to Nuxt v3 RC 11. I haven't had a problem until last Thursday. 

### What is actually happening?
A ton of calls are being made to the endpoint **/api/_supabase/session**, even when nobody is on the webpage.

<img width="1291" alt="Screen Shot 2022-09-25 at 2 20 12 PM" src="https://user-images.githubusercontent.com/5698327/192163854-afeb3d39-6711-4518-932b-c836ed707768.png">

**Comment by flapili** [comment]
same issue

**Comment by warflash** [comment]
Same issue, it's spamming really bad. Did one of you find a workaround? Or just block that path at firewall level for now

**Comment by larbish** [comment]
Can you provide a repository to reproduce ? I will ask [@orinokai](https://github.com/orinokai) to take a look at it.

**Comment by larbish** [comment]
Closing in favor of #101 (merging all Netlify issues)

**Comment by warflash** [comment]
Fyi, the same is happening on vercel for us so not strictly netlify related
