### ISSUE TITLE
How do I sign out completely?

### ISSUE THREAD

**Issue by yu-kani** [nuxt-modules/supabase#81]
### Version
@nuxtjs/supabase: "^0.1.27"
nuxt: "^3.0.0-rc.11"

### Question
The first time you used your Twitter provider for sign-in, you selected your account.

Thereafter, when signing in after signing out, the account selection screen is skipped and the user is automatically logged in.

Is it possible to sign out completely?
In the AuthModule, logout({returnTo: '/url' })

Please tell me, thank you.

`
signin
`
``` javascript
const onSignIn = async (provider) => {
  const { error } = await $nuxtApp.$supabase.auth.signIn(
    { provider },
    { redirectTo: "http://localhost:3000/test") }
  );
}
```

`
signout
`
``` javascript
const onSignOut = async () => {
  const { error } = await $nuxtApp.$supabase.auth.signOut();
  navigateTo("/");
};
```

**Comment by yu-kani** [comment]
This required a different flow than at sign-out.
A parameter was required for the Twitter API when authenticating a Twitter account.

`
Endpoint
`
https://api.twitter.com/oauth/authenticate
`
Params
`
force_login=true


The option to pass query parameters during sign-in may not be working. If you know, could you please give us some information?

`
@nuxtjs/supabase 0.1.27
`
``` javascript
const onSignIn = async (provider) => {
  const { error } = await $nuxtApp.$supabase.auth.signIn(
    { provider },
    { queryParams: { force_login: "true"} }
  );
}
```

`
@nuxtjs/supabase 0.2.0-19
`
``` javascript
const onSignInWithOAuth = async (provider) => {
  const redirectTo = $config.public.SUPABASE_REDIRECT_TO_CALLBACK;
  const { user, session, error } =
    await $nuxtApp.$supabase.auth.signInWithOAuth({
      provider,
      options: { redirectTo: redirectTo, queryParams: { force_login: "true" } },
    });
};
```

**Comment by cesswhite** [comment]
Have you managed to solve the SignOut problem completely?

I have the same problem, when I use the Supabase SignOut method, I make a redirect to the home page, but when I enter the login form again, the user automatically logs in.

**Comment by larbish** [comment]
This should be fixed in last version, can you please confirm ?
