### ISSUE TITLE
Signin works locally with "npm run dev", but not works when it's hosted

### ISSUE THREAD

**Issue by Solemensis** [nuxt-modules/supabase#88]
When i host my website on netlify, signIn gives 404 error instead working like it did on local.
This is console error:

![image](https://user-images.githubusercontent.com/96355888/196484527-522699cf-1e53-4449-97b7-5c1bf463a46f.png)

Version:
@nuxtjs/supabase: "^0.2.1"
nuxt: "3.0.0-rc.12"

I've hosted an example reproducible auth website on netlify:
https://luminous-haupia-12c8f2.netlify.app/

You can try to login with:
mail: myauthtest23@outlook.com // pass: 234ghj
Or create your account. (creating account works both local and hosted, but login only works locally.)

Steps to reproduce:
Just try to login

What is Expected?
useSupabaseUser value to show the user (on the screen)

What is actually happening?
useSupabaseUser value still empty after login, because console 404 error happens.

ps: my supabaseKey and supabaseUrl values matches with the supabase client object, both on localhost and netlify host.

**Comment by larbish** [comment]
Can you provide a simple case as a repository to reproduce ? Also, can you try to deploy on [Vercel](https://vercel.com/) and tell me if you have the same issue.

**Comment by Solemensis** [comment]
I tried to host it on Vercel 2-3 days ago, i’m from Turkey, they don’t support turkish phone numbers so i couldn’t register.
And, i tried hosting it on Surge yesterday, it gave the same errors.


  *   Uploaded a reproducable repo with minimal code. Just enter your Supabase url/Supabase key into .env file, and try to login.

https://github.com/Solemensis/supabase-nuxt-login_bug


  *   In local npm run dev, you can both create and login account with no problem, but in netlify host; you can create account while you can’t login. Gives 404 console. So don’t forget to host it on netlify please. Login works locally, not on host.





Kimden: Baptiste ***@***.***>
Gönderilme: 22 Ekim 2022 Cumartesi 12:59
Kime: ***@***.***>
Bilgi: Ulaş ***@***.***>; ***@***.***>
Konu: Re: [nuxt-modules/supabase] Signin works locally with "npm run dev", but not works when it's hosted (Issue #88)


Can you provide a simple case as a repository to reproduce ? Also, can you try to deploy on Vercel<https://vercel.com/> and tell me if you have the same issue.

**Comment by Solemensis** [comment]
Okay my bad, i was hosting "npm run generate" files which are for static pages, so i needed to host "npm run build" files.

But there's another problem rn, i'll try to handle it for next days. If i can't handle i'll open another issue
