### ISSUE TITLE
Error 500 on page reload (Cannot use 'in' operator to search for 'catch' in undefined)

### ISSUE THREAD

**Issue by Ponkhy** [nuxt-modules/supabase#89]
### Version
@nuxtjs/supabase: 0.2.0 and 0.2.1
nuxt: 3.0.0-rc.12 and 3.0.0-rc.11

### Steps to reproduce
I haven't quite figured out how to trigger it yet, but I mostly it happens after you stayed logged in for over a hour without doing anything and then refresh the browser window.
After a 2nd refresh it does work normally again.

### What is Expected?
Not to run into a error 500

### What is actually happening?
Showing a error 500 on page reload
```
Cannot use 'in' operator to search for 'catch' in undefined
at Module.executeAsync (./node_modules/unctx/dist/index.mjs:93:15)
at ./node_modules/@nuxtjs/supabase/dist/runtime/plugins/supabase.server.mjs:24:49
at runMicrotasks ()
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Object.callAsync (./node_modules/unctx/dist/index.mjs:53:16)
at async applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:94:23)
at async Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:104:5)
at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.mjs:30:7)
at async default (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)
at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)
```

Does anyone have a idea what could cause it?

I have already reinstalled the node_modules folder and cleared the lock file.

**Comment by Solemensis** [comment]
this was happening to me too, it was caused when there was no logged in user but something still forces to get user info to do something  in my page. So find the thing that forces your user to do something (even console.log(user) can count) and make it conditional. so if it is (console.log(user)), make it (if(user)console.log(user))

**Comment by kelyamany** [comment]
``This happens to me as well, I'm using a simple server middleware to allow incoming api requests, here is a snippet of my code too

```ts
import { serverSupabaseUser } from '#supabase/server'

export default defineEventHandler(async (event) => {
  if (!event.req.url.includes('api') || event.req.url.includes('session')) {
    return
  }
  const user = await serverSupabaseUser(event) // the exception is triggered from this call

  if (user?.aud == 'authenticated') {
    return
  }
  throw createError({
    statusCode: 401,
    statusMessage: 'Unauthorized',
    message: 'You have to login to access this path',
  })
})
```

The only solution I found is to signout and sign in again

**Comment by larbish** [comment]
I'll be glad if someone can create a repository or a stackblitz with a reproduction scenario 🙏

**Comment by Ponkhy** [comment]
> I'll be glad if someone can create a repository or a stackblitz with a reproduction scenario 🙏

Hi,
I've created a little repo for you, with it I was able to trigger the error whenever I want.
If you have any further questions please let me know!

Repo: https://github.com/Ponkhy/Nuxt-Supabase-Error-500/

**Comment by heikopaiko** [comment]
I am getting this, after the session ran out and returning to the still opened browser window/tab.

**Comment by Bryanoxx** [comment]
Hello! Just to confirm that I also have this bug, on the previous versions and the current one (`v0.2.3`) ✅

**Comment by larbish** [comment]
Hey guys. Could someone please try with last version `v0.2.4` ?

**Comment by manniL** [comment]
@larbish I think you can use `navigateTo` again, given the underlying issue was fixed in https://github.com/unjs/unctx/pull/43
