### ISSUE TITLE
Signout issues

### ISSUE THREAD

**Issue by marcusarnfast** [nuxt-modules/supabase#94]
### Version
@nuxtjs/supabase: v0.2.1
nuxt: v3.0.0-rc.12 or 3.0.0-rc.11

### Reproduction Link
https://github.com/marcusarnfast/Supabase-login-error

### Steps to reproduce
Login and sign out

### What is Expected?
User is signed out and redirected to the login page

### What is actually happening?
The user is either not signed out and a error is shown in the console. Or the user gets redirected to the login pages which then redirects back to the logged in page. <- not sure if this is a Nuxt related issue or the Supabase module.

I have tried both RC. 12 and RC. 11 on nuxt get the same issue.

"runtime-dom.esm-bundler.js:10 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at insert (http://localhost:3001/_nuxt/node_modules/.vite/deps/vue.js?v=832f51fc:7294:12)
    at move (http://localhost:3001/_nuxt/node_modules/.vite/deps/vue.js?v=832f51fc:5927:9)
    at move (http://localhost:3001/_nuxt/node_modules/.vite/deps/vue.js?v=832f51fc:5900:7)
    at move (http://localhost:3001/_nuxt/node_modules/.vite/deps/vue.js?v=832f51fc:5900:7)
    at activeBranch.transition.afterLeave (http://localhost:3001/_nuxt/node_modules/.vite/deps/vue.js?v=832f51fc:2328:15)
    at performRemove (http://localhost:3001/_nuxt/node_modules/.vite/deps/vue.js?v=832f51fc:6014:20)
    at el._leaveCb (http://localhost:3001/_nuxt/node_modules/.vite/deps/vue.js?v=832f51fc:2968:9)
    at finishLeave (http://localhost:3001/_nuxt/node_modules/.vite/deps/vue.js?v=832f51fc:7905:13)
    at resolve2 (http://localhost:3001/_nuxt/node_modules/.vite/deps/vue.js?v=832f51fc:7936:30)
    at whenTransitionEnds (http://localhost:3001/_nuxt/node_modules/.vite/deps/vue.js?v=832f51fc:8021:12)
insert @ runtime-dom.esm-bundler.js:10
move @ runtime-core.esm-bundler.js:6039
move @ runtime-core.esm-bundler.js:6009
move @ runtime-core.esm-bundler.js:6009
activeBranch.transition.afterLeave @ runtime-core.esm-bundler.js:1379
performRemove @ runtime-core.esm-bundler.js:6150
el._leaveCb @ runtime-core.esm-bundler.js:2163
finishLeave @ runtime-dom.esm-bundler.js:807
resolve2 @ runtime-dom.esm-bundler.js:838
whenTransitionEnds @ runtime-dom.esm-bundler.js:931
(anonym) @ runtime-dom.esm-bundler.js:851
requestAnimationFrame (asynkron)
(anonym) @ runtime-dom.esm-bundler.js:915
requestAnimationFrame (asynkron)
nextFrame @ runtime-dom.esm-bundler.js:914
onLeave @ runtime-dom.esm-bundler.js:843
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
callHook3 @ runtime-core.esm-bundler.js:2072
callAsyncHook @ runtime-core.esm-bundler.js:2076
leave @ runtime-core.esm-bundler.js:2177
performLeave @ runtime-core.esm-bundler.js:6157
remove2 @ runtime-core.esm-bundler.js:6162
unmount @ runtime-core.esm-bundler.js:6108
unmountComponent @ runtime-core.esm-bundler.js:6196
unmount @ runtime-core.esm-bundler.js:6081
unmountComponent @ runtime-core.esm-bundler.js:6196
unmount @ runtime-core.esm-bundler.js:6081
resolve @ runtime-core.esm-bundler.js:1390
patchSuspense @ runtime-core.esm-bundler.js:1314
process @ runtime-core.esm-bundler.js:1192
patch @ runtime-core.esm-bundler.js:5091
componentUpdateFn @ runtime-core.esm-bundler.js:5695
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5729
updateComponent @ runtime-core.esm-bundler.js:5554
processComponent @ runtime-core.esm-bundler.js:5487
patch @ runtime-core.esm-bundler.js:5085
componentUpdateFn @ runtime-core.esm-bundler.js:5695
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5729
updateComponent @ runtime-core.esm-bundler.js:5554
processComponent @ runtime-core.esm-bundler.js:5487
patch @ runtime-core.esm-bundler.js:5085
componentUpdateFn @ runtime-core.esm-bundler.js:5695
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5729
callWithErrorHandling @ runtime-core.esm-bundler.js:155
flushJobs @ runtime-core.esm-bundler.js:388
Promise.then (asynkron)
queueFlush @ runtime-core.esm-bundler.js:280
queuePostFlushCb @ runtime-core.esm-bundler.js:302
queueEffectWithSuspense @ runtime-core.esm-bundler.js:1589
scheduler @ runtime-core.esm-bundler.js:1811
triggerEffect @ reactivity.esm-bundler.js:396
triggerEffects @ reactivity.esm-bundler.js:386
triggerRefValue @ reactivity.esm-bundler.js:1002
(anonym) @ reactivity.esm-bundler.js:1136
triggerEffect @ reactivity.esm-bundler.js:396
triggerEffects @ reactivity.esm-bundler.js:381
triggerRefValue @ reactivity.esm-bundler.js:1002
(anonym) @ reactivity.esm-bundler.js:1136
triggerEffect @ reactivity.esm-bundler.js:396
triggerEffects @ reactivity.esm-bundler.js:381
triggerRefValue @ reactivity.esm-bundler.js:1002
set value @ reactivity.esm-bundler.js:1047
finalizeNavigation @ vue-router.mjs?v=8678cecd:3324
(anonym) @ vue-router.mjs?v=8678cecd:3197
Promise.then (asynkron)
pushWithRedirect @ vue-router.mjs?v=8678cecd:3164
push @ vue-router.mjs?v=8678cecd:3089
navigateTo @ router.mjs?v=8678cecd:69
(anonym) @ index.vue:31
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
getter @ runtime-core.esm-bundler.js:1736
run @ reactivity.esm-bundler.js:187
doWatch @ runtime-core.esm-bundler.js:1838
watchEffect @ runtime-core.esm-bundler.js:1656
setup @ index.vue:29
callWithErrorHandling @ runtime-core.esm-bundler.js:155
setupStatefulComponent @ runtime-core.esm-bundler.js:7204
setupComponent @ runtime-core.esm-bundler.js:7159
mountComponent @ runtime-core.esm-bundler.js:5508
processComponent @ runtime-core.esm-bundler.js:5483
patch @ runtime-core.esm-bundler.js:5085
componentUpdateFn @ runtime-core.esm-bundler.js:5622
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5729
setupRenderEffect @ runtime-core.esm-bundler.js:5743
mountComponent @ runtime-core.esm-bundler.js:5525
processComponent @ runtime-core.esm-bundler.js:5483
patch @ runtime-core.esm-bundler.js:5085
patchSuspense @ runtime-core.esm-bundler.js:1311
process @ runtime-core.esm-bundler.js:1192
patch @ runtime-core.esm-bundler.js:5091
componentUpdateFn @ runtime-core.esm-bundler.js:5695
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5729
updateComponent @ runtime-core.esm-bundler.js:5554
processComponent @ runtime-core.esm-bundler.js:5487
patch @ runtime-core.esm-bundler.js:5085
componentUpdateFn @ runtime-core.esm-bundler.js:5695
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5729
updateComponent @ runtime-core.esm-bundler.js:5554
processComponent @ runtime-core.esm-bundler.js:5487
patch @ runtime-core.esm-bundler.js:5085
componentUpdateFn @ runtime-core.esm-bundler.js:5695
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5729
callWithErrorHandling @ runtime-core.esm-bundler.js:155
flushJobs @ runtime-core.esm-bundler.js:388
Promise.then (asynkron)
queueFlush @ runtime-core.esm-bundler.js:280
queuePostFlushCb @ runtime-core.esm-bundler.js:302
queueEffectWithSuspense @ runtime-core.esm-bundler.js:1589
scheduler @ runtime-core.esm-bundler.js:1811
triggerEffect @ reactivity.esm-bundler.js:396
triggerEffects @ reactivity.esm-bundler.js:386
triggerRefValue @ reactivity.esm-bundler.js:1002
(anonym) @ reactivity.esm-bundler.js:1136
triggerEffect @ reactivity.esm-bundler.js:396
triggerEffects @ reactivity.esm-bundler.js:381
triggerRefValue @ reactivity.esm-bundler.js:1002
(anonym) @ reactivity.esm-bundler.js:1136
triggerEffect @ reactivity.esm-bundler.js:396
triggerEffects @ reactivity.esm-bundler.js:381
triggerRefValue @ reactivity.esm-bundler.js:1002
set value @ reactivity.esm-bundler.js:1047
finalizeNavigation @ vue-router.mjs?v=8678cecd:3324
(anonym) @ vue-router.mjs?v=8678cecd:3197
Promise.then (asynkron)
pushWithRedirect @ vue-router.mjs?v=8678cecd:3164
push @ vue-router.mjs?v=8678cecd:3089
signOut @ auth.vue:24
await in signOut (asynkron)
_createElementVNode.onClick._cache.<computed>._cache.<computed> @ auth.vue:4
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:339"

**Comment by larbish** [comment]
In your `logout` method have you tried to watch user value:
 ```
  watch(user, () => {
    navigateTo('/')
  })
````
You wait for Supabase session event before redirect.

**Comment by marcusarnfast** [comment]
I think I got it to work. - Please note that you are using the watchEffect() in the supabase demo

What do you mean by? "Supabase session event".

**Comment by larbish** [comment]
`watchEffect` could also work indeed. Similar behaviour. You can check the difference in [Vue documentation](https://vuejs.org/guide/essentials/watchers.html#watcheffect).

Supabase session event: https://supabase.com/docs/reference/javascript/auth-onauthstatechange. This is transparent for you because handled by the module. 

Please close this issue if it's fixed ✅
