### ISSUE TITLE
How do I assign Typescript type when receiving data?

### ISSUE THREAD

**Issue by phillipmohr** [nuxt-modules/supabase#96]
Hey, I'm getting selecting data and I want to add my Typescript interface. How can I do that? I tried it like this

```js
const client = useSupabaseClient()
import { IMenu } from '@/types/admin'

const { data, error }: { data: PostgrestResponse<IMenu>, error } = await client
    .from('admin_menu')
    .select(`
        name,
        items:admin_menu_items (
            name,
            url,
            icon
        )
    `)
```

I'm not sure if this is somehow the right way to do it, but I get the error `Cannot find name 'PostgrestResponse'.ts(2304)`

How can I import PostgrestResponse as a type or is there another approach?

**Comment by kevcodez** [comment]
The `useSupabaseClient` function has a generic type parameter, so you can pass your database types in there.

```ts
export interface Database {
  public: {
    Tables: {
      blog: {
        Row: {
          id: string
          info: Json | null
          topics: string[] | null
        }
        Insert: {
          id: string
          info?: Json | null
          topics?: string[] | null
        }
        Update: {
          id?: string
          info?: Json | null
          topics?: string[] | null
        }
      }
}
```

You can actually use the [supabase-cli](https://github.com/supabase/cli) to generate types for your entire schema.

Install the supabase-cli, link your project using `supabase link` and then generate the types using `supabase gen types typescript --linked > lib/database.types.ts`. Now, you can import the `Database` interface from the generated `database.types.ts`.

```ts
const supabaseClient = useSupabaseClient<Database>()

// This it typed now
const blogs = await supabaseClient.from('blog').select('*')
```

<img width="590" alt="Screenshot 2022-11-20 at 17 15 54" src="https://user-images.githubusercontent.com/14073399/202913157-a7e291da-0c4c-40b3-90b7-2eca1e076162.png">

**Comment by larbish** [comment]
Indeed it has been fixed in https://github.com/nuxt-modules/supabase/commit/fd751d7e50c63c48df9e03763458cc826409ff35, thanks for the details @kevcodez !
